# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/SessionErrorEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/SessionErrorEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!oaa/common/SessionErrorEnum.proto\x12\x0foaa.proto.enums\"\xa3\x03\n\x0cSessionError\"\x92\x03\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nNO_SENSORS\x10\x01\x12\x18\n\x14\x42\x41\x44_MIC_AUDIO_CONFIG\x10\x06\x12\x14\n\x10\x42\x41\x44_AUDIO_CONFIG\x10\x07\x12\x18\n\x14MISSING_AUDIO_CONFIG\x10\x08\x12\x18\n\x14NAV_NO_IMAGE_OPTIONS\x10\t\x12\r\n\tBAD_VIDEO\x10\x0c\x12\x11\n\rMISSING_VIDEO\x10\r\x12\x13\n\x0fNO_VIDEO_CONFIG\x10\x11\x12\x18\n\x14\x42\x41\x44_CODEC_RESOLUTION\x10\x12\x12\x1a\n\x16\x42\x41\x44_DISPLAY_RESOLUTION\x10\x13\x12\x0b\n\x07\x42\x41\x44_FPS\x10\x14\x12\x0e\n\nNO_DENSITY\x10\x15\x12\x0f\n\x0b\x42\x41\x44_DENSITY\x10\x16\x12\x0c\n\x08NO_INPUT\x10\x1a\x12\x15\n\x11VIDEO_ACK_TIMEOUT\x10\x30\x12\x10\n\x0cPING_TIMEOUT\x10\x39\x12\x1c\n\x18MULTIPLE_DISPLAY_CONFIGS\x10:\x12\x1c\n\x18\x41UTH_FAILED_OBSOLETE_SSL\x10Kb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.SessionErrorEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONERROR']._serialized_start=55
  _globals['_SESSIONERROR']._serialized_end=474
  _globals['_SESSIONERROR_ENUM']._serialized_start=72
  _globals['_SESSIONERROR_ENUM']._serialized_end=474
# @@protoc_insertion_point(module_scope)
