# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/WirelessTcpConfigurationData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/WirelessTcpConfigurationData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-oaa/common/WirelessTcpConfigurationData.proto\x12\x0eoaa.proto.data\"\x85\x01\n\x18WirelessTcpConfiguration\x12%\n\x1dsocket_receive_buffer_size_kb\x18\x01 \x01(\r\x12\"\n\x1asocket_send_buffer_size_kb\x18\x02 \x01(\r\x12\x1e\n\x16socket_read_timeout_ms\x18\x03 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.WirelessTcpConfigurationData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIRELESSTCPCONFIGURATION']._serialized_start=66
  _globals['_WIRELESSTCPCONFIGURATION']._serialized_end=199
# @@protoc_insertion_point(module_scope)
