# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/ButtonEventsData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/ButtonEventsData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.input import ButtonEventData_pb2 as oaa_dot_input_dot_ButtonEventData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n oaa/input/ButtonEventsData.proto\x12\x0eoaa.proto.data\x1a\x1foaa/input/ButtonEventData.proto\"B\n\x0c\x42uttonEvents\x12\x32\n\rbutton_events\x18\x01 \x03(\x0b\x32\x1b.oaa.proto.data.ButtonEvent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.ButtonEventsData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUTTONEVENTS']._serialized_start=85
  _globals['_BUTTONEVENTS']._serialized_end=151
# @@protoc_insertion_point(module_scope)
