# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/ButtonCodeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/ButtonCodeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eoaa/input/ButtonCodeEnum.proto\x12\x0foaa.proto.enums\"\x88\x05\n\nButtonCode\"\xf9\x04\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04HOME\x10\x03\x12\x08\n\x04\x42\x41\x43K\x10\x04\x12\x08\n\x04\x43\x41LL\x10\x05\x12\x0b\n\x07\x45NDCALL\x10\x06\x12\x0b\n\x07\x44PAD_UP\x10\x13\x12\r\n\tDPAD_DOWN\x10\x14\x12\r\n\tDPAD_LEFT\x10\x15\x12\x0e\n\nDPAD_RIGHT\x10\x16\x12\x0f\n\x0b\x44PAD_CENTER\x10\x17\x12\r\n\tVOLUME_UP\x10\x18\x12\x0f\n\x0bVOLUME_DOWN\x10\x19\x12\x0f\n\x0bHEADSETHOOK\x10O\x12\x08\n\x04MENU\x10R\x12\n\n\x06SEARCH\x10T\x12\x14\n\x10MEDIA_PLAY_PAUSE\x10U\x12\x0e\n\nMEDIA_STOP\x10V\x12\x0e\n\nMEDIA_NEXT\x10W\x12\x12\n\x0eMEDIA_PREVIOUS\x10X\x12\x0e\n\nMEDIA_PLAY\x10~\x12\x0f\n\x0bMEDIA_PAUSE\x10\x7f\x12\x10\n\x0bVOLUME_MUTE\x10\xa4\x01\x12\n\n\x05MUSIC\x10\xd1\x01\x12\x0b\n\x06\x41SSIST\x10\xdb\x01\x12\x11\n\x0cVOICE_ASSIST\x10\xe7\x01\x12\x16\n\x11NAVIGATE_PREVIOUS\x10\x84\x02\x12\x12\n\rNAVIGATE_NEXT\x10\x85\x02\x12\x10\n\x0bNAVIGATE_IN\x10\x86\x02\x12\x11\n\x0cNAVIGATE_OUT\x10\x87\x02\x12\x0e\n\x08SENTINEL\x10\xff\xff\x03\x12\x12\n\x0cSCROLL_WHEEL\x10\x80\x80\x04\x12\x0b\n\x05MEDIA\x10\x81\x80\x04\x12\x10\n\nNAVIGATION\x10\x82\x80\x04\x12\x0b\n\x05RADIO\x10\x83\x80\x04\x12\t\n\x03TEL\x10\x84\x80\x04\x12\x14\n\x0ePRIMARY_BUTTON\x10\x85\x80\x04\x12\x16\n\x10SECONDARY_BUTTON\x10\x86\x80\x04\x12\x15\n\x0fTERTIARY_BUTTON\x10\x87\x80\x04\x12\x0f\n\tTURN_CARD\x10\x88\x80\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.ButtonCodeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUTTONCODE']._serialized_start=52
  _globals['_BUTTONCODE']._serialized_end=700
  _globals['_BUTTONCODE_ENUM']._serialized_start=67
  _globals['_BUTTONCODE_ENUM']._serialized_end=700
# @@protoc_insertion_point(module_scope)
