# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/HapticFeedbackTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/HapticFeedbackTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/input/HapticFeedbackTypeEnum.proto\x12\x0foaa.proto.enums\"\x97\x01\n\x12HapticFeedbackType\"\x80\x01\n\x04\x45num\x12\x13\n\x0f\x46\x45\x45\x44\x42\x41\x43K_SELECT\x10\x01\x12\x19\n\x15\x46\x45\x45\x44\x42\x41\x43K_FOCUS_CHANGE\x10\x02\x12\x18\n\x14\x46\x45\x45\x44\x42\x41\x43K_DRAG_SELECT\x10\x03\x12\x17\n\x13\x46\x45\x45\x44\x42\x41\x43K_DRAG_START\x10\x04\x12\x15\n\x11\x46\x45\x45\x44\x42\x41\x43K_DRAG_END\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.HapticFeedbackTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HAPTICFEEDBACKTYPE']._serialized_start=60
  _globals['_HAPTICFEEDBACKTYPE']._serialized_end=211
  _globals['_HAPTICFEEDBACKTYPE_ENUM']._serialized_start=83
  _globals['_HAPTICFEEDBACKTYPE_ENUM']._serialized_end=211
# @@protoc_insertion_point(module_scope)
