# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/RelativeInputEventsData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/RelativeInputEventsData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.input import RelativeInputEventData_pb2 as oaa_dot_input_dot_RelativeInputEventData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/input/RelativeInputEventsData.proto\x12\x0eoaa.proto.data\x1a&oaa/input/RelativeInputEventData.proto\"X\n\x13RelativeInputEvents\x12\x41\n\x15relative_input_events\x18\x01 \x03(\x0b\x32\".oaa.proto.data.RelativeInputEvent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.RelativeInputEventsData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELATIVEINPUTEVENTS']._serialized_start=99
  _globals['_RELATIVEINPUTEVENTS']._serialized_end=187
# @@protoc_insertion_point(module_scope)
