# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/InputEventIndicationMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/InputEventIndicationMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.input import TouchEventData_pb2 as oaa_dot_input_dot_TouchEventData__pb2
from oaa.input import ButtonEventsData_pb2 as oaa_dot_input_dot_ButtonEventsData__pb2
from oaa.input import AbsoluteInputEventsData_pb2 as oaa_dot_input_dot_AbsoluteInputEventsData__pb2
from oaa.input import RelativeInputEventsData_pb2 as oaa_dot_input_dot_RelativeInputEventsData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+oaa/input/InputEventIndicationMessage.proto\x12\x12oaa.proto.messages\x1a\x1eoaa/input/TouchEventData.proto\x1a oaa/input/ButtonEventsData.proto\x1a\'oaa/input/AbsoluteInputEventsData.proto\x1a\'oaa/input/RelativeInputEventsData.proto\"\xc8\x02\n\x14InputEventIndication\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12/\n\x0btouch_event\x18\x03 \x01(\x0b\x32\x1a.oaa.proto.data.TouchEvent\x12\x32\n\x0c\x62utton_event\x18\x04 \x01(\x0b\x32\x1c.oaa.proto.data.ButtonEvents\x12\x41\n\x14\x61\x62solute_input_event\x18\x05 \x01(\x0b\x32#.oaa.proto.data.AbsoluteInputEvents\x12\x41\n\x14relative_input_event\x18\x06 \x01(\x0b\x32#.oaa.proto.data.RelativeInputEvents\x12\x32\n\x0etouchpad_event\x18\x07 \x01(\x0b\x32\x1a.oaa.proto.data.TouchEvent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.InputEventIndicationMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTEVENTINDICATION']._serialized_start=216
  _globals['_INPUTEVENTINDICATION']._serialized_end=544
# @@protoc_insertion_point(module_scope)
