# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/TouchPadConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/TouchPadConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/input/TouchPadConfigData.proto\x12\x0eoaa.proto.data\"\xb8\x01\n\x0eTouchPadConfig\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\x15\n\rui_navigation\x18\x03 \x01(\x08\x12\x16\n\x0ephysical_width\x18\x04 \x01(\x05\x12\x17\n\x0fphysical_height\x18\x05 \x01(\x05\x12\x13\n\x0bui_absolute\x18\x06 \x01(\x08\x12\x15\n\rtap_as_select\x18\x07 \x01(\x08\x12\x13\n\x0bsensitivity\x18\x08 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.TouchPadConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOUCHPADCONFIG']._serialized_start=55
  _globals['_TOUCHPADCONFIG']._serialized_end=239
# @@protoc_insertion_point(module_scope)
