# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/bluetooth/BluetoothPairingRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/bluetooth/BluetoothPairingRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.bluetooth import BluetoothPairingMethodEnum_pb2 as oaa_dot_bluetooth_dot_BluetoothPairingMethodEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2oaa/bluetooth/BluetoothPairingRequestMessage.proto\x12\x12oaa.proto.messages\x1a.oaa/bluetooth/BluetoothPairingMethodEnum.proto\"\xcd\x01\n\x17\x42luetoothPairingRequest\x12\x1a\n\rphone_address\x18\x01 \x01(\tH\x00\x88\x01\x01\x12I\n\x0epairing_method\x18\x02 \x01(\x0e\x32,.oaa.proto.enums.BluetoothPairingMethod.EnumH\x01\x88\x01\x01\x12\x17\n\nphone_name\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x10\n\x0e_phone_addressB\x11\n\x0f_pairing_methodB\r\n\x0b_phone_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.bluetooth.BluetoothPairingRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHPAIRINGREQUEST']._serialized_start=123
  _globals['_BLUETOOTHPAIRINGREQUEST']._serialized_end=328
# @@protoc_insertion_point(module_scope)
