# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/bluetooth/BluetoothPairingMethodEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/bluetooth/BluetoothPairingMethodEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.oaa/bluetooth/BluetoothPairingMethodEnum.proto\x12\x0foaa.proto.enums\"g\n\x16\x42luetoothPairingMethod\"M\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03OOB\x10\x01\x12\x16\n\x12NUMERIC_COMPARISON\x10\x02\x12\x11\n\rPASSKEY_ENTRY\x10\x03\x12\x07\n\x03PIN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.bluetooth.BluetoothPairingMethodEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHPAIRINGMETHOD']._serialized_start=67
  _globals['_BLUETOOTHPAIRINGMETHOD']._serialized_end=170
  _globals['_BLUETOOTHPAIRINGMETHOD_ENUM']._serialized_start=93
  _globals['_BLUETOOTHPAIRINGMETHOD_ENUM']._serialized_end=170
# @@protoc_insertion_point(module_scope)
