audio.media.channel_count: 2
audio.media.sample_rate: 48000
audio.speech.sample_rate: 48000
audio.system.sample_rate: 16000
hu.make: Nemo
hu.model: NemoHeadUnit-Wireless
hu.name: NemoHeadUnit
hu.sw_version: '2.0'
nav.image.height: 64
nav.image.width: 64
nav.min_interval_ms: 500
touch.height: 720
touch.width: 1280
video.dpi: 140
video.fps: _30
video.resolution: VIDEO_1280x720
