# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/AdditionalVideoConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/AdditionalVideoConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)oaa/video/AdditionalVideoConfigData.proto\x12\x0eoaa.proto.data\"\xaf\x03\n\x15\x41\x64\x64itionalVideoConfig\x12<\n\x0emin_resolution\x18\x01 \x01(\x0b\x32$.oaa.proto.data.VideoResolutionRange\x12<\n\x0emax_resolution\x18\x02 \x01(\x0b\x32$.oaa.proto.data.VideoResolutionRange\x12\x42\n\x14preferred_resolution\x18\x03 \x01(\x0b\x32$.oaa.proto.data.VideoResolutionRange\x12)\n\x08ui_theme\x18\x04 \x01(\x0e\x32\x17.oaa.proto.data.UITheme\x12\x35\n\x12hidden_ui_elements\x18\x05 \x03(\x0e\x32\x19.oaa.proto.data.UIElement\x12\x39\n\x0eresize_actions\x18\x06 \x03(\x0b\x32!.oaa.proto.data.VideoResizeAction\x12\x39\n\x0emargin_configs\x18\x07 \x03(\x0b\x32!.oaa.proto.data.VideoMarginConfig\"S\n\x14VideoResolutionRange\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0f\n\x07\x64\x65nsity\x18\x03 \x01(\r\x12\x0b\n\x03\x66ps\x18\x04 \x01(\r\"E\n\x11VideoResizeAction\x12\x30\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32 .oaa.proto.data.ResizeActionType\"@\n\x11VideoMarginConfig\x12+\n\x06insets\x18\x01 \x01(\x0b\x32\x1b.oaa.proto.data.VideoInsets\"G\n\x0bVideoInsets\x12\x0c\n\x04left\x18\x01 \x01(\r\x12\x0b\n\x03top\x18\x02 \x01(\r\x12\r\n\x05right\x18\x03 \x01(\r\x12\x0e\n\x06\x62ottom\x18\x04 \x01(\r*H\n\x07UITheme\x12\x16\n\x12UI_THEME_AUTOMATIC\x10\x00\x12\x12\n\x0eUI_THEME_LIGHT\x10\x01\x12\x11\n\rUI_THEME_DARK\x10\x02*\xc8\x01\n\tUIElement\x12\x16\n\x12UI_ELEMENT_UNKNOWN\x10\x00\x12\x14\n\x10UI_ELEMENT_CLOCK\x10\x01\x12\x1c\n\x18UI_ELEMENT_BATTERY_LEVEL\x10\x02\x12\x1b\n\x17UI_ELEMENT_PHONE_SIGNAL\x10\x03\x12#\n\x1fUI_ELEMENT_NATIVE_UI_AFFORDANCE\x10\x04\x12-\n)UI_ELEMENT_NAVIGATION_TURN_DATA_AVAILABLE\x10\x05*a\n\x10ResizeActionType\x12\x12\n\x0e\x41\x43TION_UNKNOWN\x10\x00\x12\x1c\n\x18\x41\x43TION_RESIZE_TO_SMALLER\x10\x01\x12\x1b\n\x17\x41\x43TION_RESIZE_TO_LARGER\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.AdditionalVideoConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UITHEME']._serialized_start=790
  _globals['_UITHEME']._serialized_end=862
  _globals['_UIELEMENT']._serialized_start=865
  _globals['_UIELEMENT']._serialized_end=1065
  _globals['_RESIZEACTIONTYPE']._serialized_start=1067
  _globals['_RESIZEACTIONTYPE']._serialized_end=1164
  _globals['_ADDITIONALVIDEOCONFIG']._serialized_start=62
  _globals['_ADDITIONALVIDEOCONFIG']._serialized_end=493
  _globals['_VIDEORESOLUTIONRANGE']._serialized_start=495
  _globals['_VIDEORESOLUTIONRANGE']._serialized_end=578
  _globals['_VIDEORESIZEACTION']._serialized_start=580
  _globals['_VIDEORESIZEACTION']._serialized_end=649
  _globals['_VIDEOMARGINCONFIG']._serialized_start=651
  _globals['_VIDEOMARGINCONFIG']._serialized_end=715
  _globals['_VIDEOINSETS']._serialized_start=717
  _globals['_VIDEOINSETS']._serialized_end=788
# @@protoc_insertion_point(module_scope)
