# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/UpdateHuUiConfigResponse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/UpdateHuUiConfigResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/video/UpdateHuUiConfigResponse.proto\x12\x12oaa.proto.messages\"S\n\x18UpdateHuUiConfigResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.oaa.proto.messages.ThemingTokensStatus*i\n\x13ThemingTokensStatus\x12\x18\n\x14THEMING_TOKENS_ERROR\x10\x00\x12\x1b\n\x17THEMING_TOKENS_ACCEPTED\x10\x01\x12\x1b\n\x17THEMING_TOKENS_REJECTED\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.UpdateHuUiConfigResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THEMINGTOKENSSTATUS']._serialized_start=149
  _globals['_THEMINGTOKENSSTATUS']._serialized_end=254
  _globals['_UPDATEHUUICONFIGRESPONSE']._serialized_start=64
  _globals['_UPDATEHUUICONFIGRESPONSE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
