# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/VideoFocusModeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/VideoFocusModeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/video/VideoFocusModeEnum.proto\x12\x0foaa.proto.enums\"q\n\x0eVideoFocusMode\"_\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\r\n\tPROJECTED\x10\x01\x12\n\n\x06NATIVE\x10\x02\x12\x14\n\x10NATIVE_TRANSIENT\x10\x03\x12\x1c\n\x18PROJECTED_NO_INPUT_FOCUS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.VideoFocusModeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFOCUSMODE']._serialized_start=55
  _globals['_VIDEOFOCUSMODE']._serialized_end=168
  _globals['_VIDEOFOCUSMODE_ENUM']._serialized_start=73
  _globals['_VIDEOFOCUSMODE_ENUM']._serialized_end=168
# @@protoc_insertion_point(module_scope)
