# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/VideoFocusRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/VideoFocusRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.video import VideoFocusModeEnum_pb2 as oaa_dot_video_dot_VideoFocusModeEnum__pb2
from oaa.video import VideoFocusReasonEnum_pb2 as oaa_dot_video_dot_VideoFocusReasonEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/video/VideoFocusRequestMessage.proto\x12\x12oaa.proto.messages\x1a\"oaa/video/VideoFocusModeEnum.proto\x1a$oaa/video/VideoFocusReasonEnum.proto\"\x8b\x01\n\x11VideoFocusRequest\x12\x38\n\nfocus_mode\x18\x02 \x01(\x0e\x32$.oaa.proto.enums.VideoFocusMode.Enum\x12<\n\x0c\x66ocus_reason\x18\x03 \x01(\x0e\x32&.oaa.proto.enums.VideoFocusReason.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.VideoFocusRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFOCUSREQUEST']._serialized_start=139
  _globals['_VIDEOFOCUSREQUEST']._serialized_end=278
# @@protoc_insertion_point(module_scope)
