# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/VideoResolutionEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/VideoResolutionEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/video/VideoResolutionEnum.proto\x12\x0foaa.proto.enums\"\xdd\x01\n\x0fVideoResolution\"\xc9\x01\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x11\n\rVIDEO_800x480\x10\x01\x12\x12\n\x0eVIDEO_1280x720\x10\x02\x12\x13\n\x0fVIDEO_1920x1080\x10\x03\x12\x13\n\x0fVIDEO_2560x1440\x10\x04\x12\x13\n\x0fVIDEO_3840x2160\x10\x05\x12\x12\n\x0eVIDEO_720x1280\x10\x06\x12\x13\n\x0fVIDEO_1080x1920\x10\x07\x12\x13\n\x0fVIDEO_1440x2560\x10\x08\x12\x13\n\x0fVIDEO_2160x3840\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.VideoResolutionEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEORESOLUTION']._serialized_start=57
  _globals['_VIDEORESOLUTION']._serialized_end=278
  _globals['_VIDEORESOLUTION_ENUM']._serialized_start=77
  _globals['_VIDEORESOLUTION_ENUM']._serialized_end=278
# @@protoc_insertion_point(module_scope)
