# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiSetupMessageEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiSetupMessageEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/wifi/WifiSetupMessageEnum.proto\x12\x0foaa.proto.enums\"\xff\x01\n\x10WifiSetupMessage\"\xea\x01\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x11\n\rREQUEST_START\x10\x01\x12\x10\n\x0cREQUEST_INFO\x10\x02\x12\x11\n\rRESPONSE_INFO\x10\x03\x12\x13\n\x0fVERSION_REQUEST\x10\x04\x12\x14\n\x10VERSION_RESPONSE\x10\x05\x12\x12\n\x0e\x43ONNECT_STATUS\x10\x06\x12\x12\n\x0eRESPONSE_START\x10\x07\x12\x10\n\x0cPING_REQUEST\x10\x08\x12\x11\n\rPING_RESPONSE\x10\t\x12\x18\n\x14\x43ONNECTION_REJECTION\x10\n\x12\x0e\n\nSETUP_INFO\x10\x0b')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiSetupMessageEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISETUPMESSAGE']._serialized_start=57
  _globals['_WIFISETUPMESSAGE']._serialized_end=312
  _globals['_WIFISETUPMESSAGE_ENUM']._serialized_start=78
  _globals['_WIFISETUPMESSAGE_ENUM']._serialized_end=312
# @@protoc_insertion_point(module_scope)
