# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiPingMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiPingMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eoaa/wifi/WifiPingMessage.proto\x12\x12oaa.proto.messages\"=\n\x0fWifiPingRequest\x12\x19\n\x0ctimestamp_ns\x18\x01 \x01(\x03H\x00\x88\x01\x01\x42\x0f\n\r_timestamp_ns\">\n\x10WifiPingResponse\x12\x19\n\x0ctimestamp_ns\x18\x01 \x01(\x03H\x00\x88\x01\x01\x42\x0f\n\r_timestamp_nsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiPingMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIPINGREQUEST']._serialized_start=54
  _globals['_WIFIPINGREQUEST']._serialized_end=115
  _globals['_WIFIPINGRESPONSE']._serialized_start=117
  _globals['_WIFIPINGRESPONSE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
