# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiAccessPointTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiAccessPointTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/wifi/WifiAccessPointTypeEnum.proto\x12\x0foaa.proto.enums\"F\n\x13WifiAccessPointType\"/\n\x04\x45num\x12\x13\n\x0f\x41P_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0e\x41P_TYPE_STATIC\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiAccessPointTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIACCESSPOINTTYPE']._serialized_start=59
  _globals['_WIFIACCESSPOINTTYPE']._serialized_end=129
  _globals['_WIFIACCESSPOINTTYPE_ENUM']._serialized_start=82
  _globals['_WIFIACCESSPOINTTYPE_ENUM']._serialized_end=129
# @@protoc_insertion_point(module_scope)
