# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiSetupInfoMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiSetupInfoMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import FeatureFlagsData_pb2 as oaa_dot_common_dot_FeatureFlagsData__pb2
from oaa.wifi import WifiSecurityModeEnum_pb2 as oaa_dot_wifi_dot_WifiSecurityModeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/wifi/WifiSetupInfoMessage.proto\x12\x12oaa.proto.messages\x1a!oaa/common/FeatureFlagsData.proto\x1a#oaa/wifi/WifiSecurityModeEnum.proto\"\x9d\x01\n\x0fWifiNetworkInfo\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\r\n\x05\x62ssid\x18\x02 \x01(\t\x12\x12\n\npassphrase\x18\x03 \x01(\t\x12=\n\rsecurity_mode\x18\x04 \x01(\x0e\x32&.oaa.proto.enums.WifiSecurityMode.Enum\x12\x1a\n\x12supported_channels\x18\x06 \x03(\x05\"\x12\n\x10WifiSetupPayload\"\xc5\x01\n\rWifiSetupInfo\x12\x12\n\nsetup_type\x18\x01 \x01(\x05\x12\x13\n\x0bsetup_state\x18\x02 \x01(\x05\x12\x12\n\nsetup_data\x18\x03 \x01(\x0c\x12;\n\rsetup_payload\x18\x04 \x01(\x0b\x32$.oaa.proto.messages.WifiSetupPayload\x12:\n\rfeature_flags\x18\x05 \x01(\x0b\x32#.oaa.proto.data.VersionFeatureFlags')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiSetupInfoMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFINETWORKINFO']._serialized_start=132
  _globals['_WIFINETWORKINFO']._serialized_end=289
  _globals['_WIFISETUPPAYLOAD']._serialized_start=291
  _globals['_WIFISETUPPAYLOAD']._serialized_end=309
  _globals['_WIFISETUPINFO']._serialized_start=312
  _globals['_WIFISETUPINFO']._serialized_end=509
# @@protoc_insertion_point(module_scope)
