# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiCredentialsResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiCredentialsResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-oaa/wifi/WifiCredentialsResponseMessage.proto\x12\x12oaa.proto.messages\"\xbc\x01\n\x17WifiCredentialsResponse\x12\x12\n\npassphrase\x18\x01 \x01(\t\x12\x45\n\rsecurity_mode\x18\x02 \x01(\x0e\x32..oaa.proto.messages.WifiCredentialSecurityMode\x12\x0c\n\x04ssid\x18\x03 \x01(\t\x12\x38\n\x06status\x18\x05 \x01(\x0e\x32(.oaa.proto.messages.WifiCredentialStatus*\xe1\x02\n\x1aWifiCredentialSecurityMode\x12\x14\n\x10SECURITY_UNKNOWN\x10\x00\x12\x11\n\rSECURITY_OPEN\x10\x01\x12\x13\n\x0fSECURITY_WEP_64\x10\x02\x12\x14\n\x10SECURITY_WEP_128\x10\x03\x12\x19\n\x15SECURITY_WPA_PERSONAL\x10\x04\x12\x1a\n\x16SECURITY_WPA2_PERSONAL\x10\x05\x12\x1e\n\x1aSECURITY_WPA_WPA2_PERSONAL\x10\x06\x12\x1b\n\x17SECURITY_WPA_ENTERPRISE\x10\x07\x12\x1c\n\x18SECURITY_WPA2_ENTERPRISE\x10\x08\x12 \n\x1cSECURITY_WPA_WPA2_ENTERPRISE\x10\t\x12\x1a\n\x16SECURITY_WPA3_PERSONAL\x10\n\x12\x1f\n\x1bSECURITY_WPA2_WPA3_PERSONAL\x10\x0b*N\n\x14WifiCredentialStatus\x12\x18\n\x14\x43REDENTIAL_STATUS_OK\x10\x00\x12\x1c\n\x18\x43REDENTIAL_STATUS_FAILED\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiCredentialsResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICREDENTIALSECURITYMODE']._serialized_start=261
  _globals['_WIFICREDENTIALSECURITYMODE']._serialized_end=614
  _globals['_WIFICREDENTIALSTATUS']._serialized_start=616
  _globals['_WIFICREDENTIALSTATUS']._serialized_end=694
  _globals['_WIFICREDENTIALSRESPONSE']._serialized_start=70
  _globals['_WIFICREDENTIALSRESPONSE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
