# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiVersionResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiVersionResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import SessionInfoData_pb2 as oaa_dot_common_dot_SessionInfoData__pb2
from oaa.wifi import WifiChannelTypeEnum_pb2 as oaa_dot_wifi_dot_WifiChannelTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)oaa/wifi/WifiVersionResponseMessage.proto\x12\x12oaa.proto.messages\x1a oaa/common/SessionInfoData.proto\x1a\"oaa/wifi/WifiChannelTypeEnum.proto\"\x84\x02\n\x13WifiVersionResponse\x12\x15\n\rmajor_version\x18\x01 \x01(\x05\x12\x15\n\rminor_version\x18\x02 \x01(\x05\x12\x15\n\rdevice_serial\x18\x03 \x01(\t\x12\x16\n\x0eversion_status\x18\x04 \x01(\x05\x12I\n\x1aselected_wifi_channel_type\x18\x05 \x01(\x0e\x32%.oaa.proto.enums.WifiChannelType.Enum\x12\x31\n\x0csession_info\x18\x06 \x01(\x0b\x32\x1b.oaa.proto.data.SessionInfo\x12\x12\n\nextra_data\x18\x07 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiVersionResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIVERSIONRESPONSE']._serialized_start=136
  _globals['_WIFIVERSIONRESPONSE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
