# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiDirectConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiDirectConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/wifi/WifiDirectConfigData.proto\x12\x0eoaa.proto.data\"\xae\x01\n\x10WifiDirectConfig\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65vice_address\x18\x02 \x01(\t\x12\x0c\n\x04ssid\x18\x03 \x01(\t\x12\x12\n\npassphrase\x18\x04 \x01(\t\x12\x38\n\x10group_owner_info\x18\x05 \x01(\x0b\x32\x1e.oaa.proto.data.GroupOwnerInfo\x12\x11\n\tfrequency\x18\x06 \x01(\x04\"\x10\n\x0eGroupOwnerInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiDirectConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIDIRECTCONFIG']._serialized_start=56
  _globals['_WIFIDIRECTCONFIG']._serialized_end=230
  _globals['_GROUPOWNERINFO']._serialized_start=232
  _globals['_GROUPOWNERINFO']._serialized_end=248
# @@protoc_insertion_point(module_scope)
