# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import NavigationImageOptionsData_pb2 as oaa_dot_navigation_dot_NavigationImageOptionsData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/navigation/NavigationChannelData.proto\x12\x0eoaa.proto.data\x1a/oaa/navigation/NavigationImageOptionsData.proto\"}\n\x11NavigationChannel\x12\x1b\n\x13minimum_interval_ms\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12=\n\rimage_options\x18\x03 \x01(\x0b\x32&.oaa.proto.data.NavigationImageOptions')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONCHANNEL']._serialized_start=111
  _globals['_NAVIGATIONCHANNEL']._serialized_end=236
# @@protoc_insertion_point(module_scope)
