# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationChannelConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationChannelConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import NavigationTypeEnum_pb2 as oaa_dot_navigation_dot_NavigationTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0oaa/navigation/NavigationChannelConfigData.proto\x12\x0eoaa.proto.data\x1a\'oaa/navigation/NavigationTypeEnum.proto\"\xaf\x01\n\x17NavigationChannelConfig\x12\x1b\n\x13minimum_interval_ms\x18\x01 \x01(\x05\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.oaa.proto.enums.NavigationType.Enum\x12\x43\n\x10image_dimensions\x18\x03 \x01(\x0b\x32).oaa.proto.data.NavigationImageDimensions\"O\n\x19NavigationImageDimensions\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x13\n\x0b\x63olor_depth\x18\x03 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationChannelConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONCHANNELCONFIG']._serialized_start=110
  _globals['_NAVIGATIONCHANNELCONFIG']._serialized_end=285
  _globals['_NAVIGATIONIMAGEDIMENSIONS']._serialized_start=287
  _globals['_NAVIGATIONIMAGEDIMENSIONS']._serialized_end=366
# @@protoc_insertion_point(module_scope)
