# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationStateMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationStateMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+oaa/navigation/NavigationStateMessage.proto\x12\x12oaa.proto.messages\"I\n\x0fNavigationState\x12\x36\n\x05state\x18\x01 \x01(\x0e\x32\'.oaa.proto.messages.NavigationStateType*w\n\x13NavigationStateType\x12\x19\n\x15NAV_STATE_UNAVAILABLE\x10\x00\x12\x14\n\x10NAV_STATE_ACTIVE\x10\x01\x12\x16\n\x12NAV_STATE_INACTIVE\x10\x02\x12\x17\n\x13NAV_STATE_REROUTING\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationStateMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONSTATETYPE']._serialized_start=142
  _globals['_NAVIGATIONSTATETYPE']._serialized_end=261
  _globals['_NAVIGATIONSTATE']._serialized_start=67
  _globals['_NAVIGATIONSTATE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
