# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationNotificationMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationNotificationMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import ManeuverTypeEnum_pb2 as oaa_dot_navigation_dot_ManeuverTypeEnum__pb2
from oaa.navigation import LaneShapeEnum_pb2 as oaa_dot_navigation_dot_LaneShapeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2oaa/navigation/NavigationNotificationMessage.proto\x12\x12oaa.proto.messages\x1a%oaa/navigation/ManeuverTypeEnum.proto\x1a\"oaa/navigation/LaneShapeEnum.proto\"\x8c\x01\n\x16NavigationNotification\x12\x31\n\x05steps\x18\x01 \x03(\x0b\x32\".oaa.proto.messages.NavigationStep\x12?\n\x0c\x64\x65stinations\x18\x02 \x03(\x0b\x32).oaa.proto.messages.NavigationDestination\"\xf1\x01\n\x0eNavigationStep\x12\x38\n\x08maneuver\x18\x01 \x01(\x0b\x32&.oaa.proto.messages.NavigationManeuver\x12\x37\n\x0binstruction\x18\x02 \x01(\x0b\x32\".oaa.proto.messages.NavigationText\x12\x31\n\x05lanes\x18\x03 \x03(\x0b\x32\".oaa.proto.messages.NavigationLane\x12\x39\n\troad_info\x18\x04 \x01(\x0b\x32&.oaa.proto.messages.NavigationRoadInfo\"\x85\x01\n\x12NavigationManeuver\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".oaa.proto.enums.ManeuverType.Enum\x12\x1e\n\x16roundabout_exit_number\x18\x02 \x01(\x05\x12\x1d\n\x15roundabout_turn_angle\x18\x03 \x01(\x05\"\x1e\n\x0eNavigationText\x12\x0c\n\x04text\x18\x01 \x01(\t\"Q\n\x0eNavigationLane\x12?\n\ndirections\x18\x01 \x03(\x0b\x32+.oaa.proto.messages.NavigationLaneDirection\"a\n\x17NavigationLaneDirection\x12.\n\x05shape\x18\x01 \x01(\x0e\x32\x1f.oaa.proto.enums.LaneShape.Enum\x12\x16\n\x0eis_recommended\x18\x02 \x01(\x08\"(\n\x12NavigationRoadInfo\x12\x12\n\nroad_names\x18\x01 \x03(\t\"n\n\x15NavigationDestination\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x44\n\x10\x63harging_station\x18\x02 \x01(\x0b\x32*.oaa.proto.messages.ChargingStationDetails\"`\n\x16\x43hargingStationDetails\x12\x17\n\x0f\x63onnector_count\x18\x01 \x01(\x05\x12\x17\n\x0f\x61vailable_count\x18\x02 \x01(\x05\x12\x14\n\x0cmax_power_kw\x18\x03 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationNotificationMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONNOTIFICATION']._serialized_start=150
  _globals['_NAVIGATIONNOTIFICATION']._serialized_end=290
  _globals['_NAVIGATIONSTEP']._serialized_start=293
  _globals['_NAVIGATIONSTEP']._serialized_end=534
  _globals['_NAVIGATIONMANEUVER']._serialized_start=537
  _globals['_NAVIGATIONMANEUVER']._serialized_end=670
  _globals['_NAVIGATIONTEXT']._serialized_start=672
  _globals['_NAVIGATIONTEXT']._serialized_end=702
  _globals['_NAVIGATIONLANE']._serialized_start=704
  _globals['_NAVIGATIONLANE']._serialized_end=785
  _globals['_NAVIGATIONLANEDIRECTION']._serialized_start=787
  _globals['_NAVIGATIONLANEDIRECTION']._serialized_end=884
  _globals['_NAVIGATIONROADINFO']._serialized_start=886
  _globals['_NAVIGATIONROADINFO']._serialized_end=926
  _globals['_NAVIGATIONDESTINATION']._serialized_start=928
  _globals['_NAVIGATIONDESTINATION']._serialized_end=1038
  _globals['_CHARGINGSTATIONDETAILS']._serialized_start=1040
  _globals['_CHARGINGSTATIONDETAILS']._serialized_end=1136
# @@protoc_insertion_point(module_scope)
