# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/radio/RadioCodecTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/radio/RadioCodecTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/radio/RadioCodecTypeEnum.proto\x12\x0foaa.proto.enums\"\xa2\x01\n\x0eRadioCodecType\"\x8f\x01\n\x04\x45num\x12\x17\n\x13RADIO_CODEC_UNKNOWN\x10\x00\x12\x16\n\x12RADIO_CODEC_ANALOG\x10\x01\x12\x12\n\x0eRADIO_CODEC_HD\x10\x02\x12\x13\n\x0fRADIO_CODEC_DAB\x10\x03\x12\x18\n\x14RADIO_CODEC_DAB_PLUS\x10\x04\x12\x13\n\x0fRADIO_CODEC_DMB\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.radio.RadioCodecTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADIOCODECTYPE']._serialized_start=56
  _globals['_RADIOCODECTYPE']._serialized_end=218
  _globals['_RADIOCODECTYPE_ENUM']._serialized_start=75
  _globals['_RADIOCODECTYPE_ENUM']._serialized_end=218
# @@protoc_insertion_point(module_scope)
