# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/radio/RadioRegionEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/radio/RadioRegionEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1foaa/radio/RadioRegionEnum.proto\x12\x0foaa.proto.enums\";\n\x0bRadioRegion\",\n\x04\x45num\x12\x12\n\x0eREGION_UNKNOWN\x10\x00\x12\x10\n\x0cREGION_ITU_1\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.radio.RadioRegionEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADIOREGION']._serialized_start=52
  _globals['_RADIOREGION']._serialized_end=111
  _globals['_RADIOREGION_ENUM']._serialized_start=67
  _globals['_RADIOREGION_ENUM']._serialized_end=111
# @@protoc_insertion_point(module_scope)
