# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/InputChannelConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/InputChannelConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.input import TouchScreenConfigData_pb2 as oaa_dot_input_dot_TouchScreenConfigData__pb2
from oaa.input import TouchPadConfigData_pb2 as oaa_dot_input_dot_TouchPadConfigData__pb2
from oaa.input import HapticFeedbackTypeEnum_pb2 as oaa_dot_input_dot_HapticFeedbackTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/input/InputChannelConfigData.proto\x12\x0eoaa.proto.data\x1a%oaa/input/TouchScreenConfigData.proto\x1a\"oaa/input/TouchPadConfigData.proto\x1a&oaa/input/HapticFeedbackTypeEnum.proto\"\x8d\x02\n\x12InputChannelConfig\x12\x1e\n\x12supported_keycodes\x18\x01 \x03(\x05\x42\x02\x10\x01\x12?\n\x14touch_screen_configs\x18\x02 \x03(\x0b\x32!.oaa.proto.data.TouchScreenConfig\x12\x38\n\x10touchpad_configs\x18\x03 \x03(\x0b\x32\x1e.oaa.proto.data.TouchPadConfig\x12H\n\x16supported_haptic_types\x18\x04 \x03(\x0e\x32(.oaa.proto.enums.HapticFeedbackType.Enum\x12\x12\n\ndisplay_id\x18\x05 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.InputChannelConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTCHANNELCONFIG'].fields_by_name['supported_keycodes']._loaded_options = None
  _globals['_INPUTCHANNELCONFIG'].fields_by_name['supported_keycodes']._serialized_options = b'\020\001'
  _globals['_INPUTCHANNELCONFIG']._serialized_start=174
  _globals['_INPUTCHANNELCONFIG']._serialized_end=443
# @@protoc_insertion_point(module_scope)
