# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/input/TouchActionEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/input/TouchActionEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1foaa/input/TouchActionEnum.proto\x12\x0foaa.proto.enums\"Y\n\x0bTouchAction\"J\n\x04\x45num\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x12\x08\n\x04\x44RAG\x10\x02\x12\x10\n\x0cPOINTER_DOWN\x10\x05\x12\x0e\n\nPOINTER_UP\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.input.TouchActionEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOUCHACTION']._serialized_start=52
  _globals['_TOUCHACTION']._serialized_end=141
  _globals['_TOUCHACTION_ENUM']._serialized_start=67
  _globals['_TOUCHACTION_ENUM']._serialized_end=141
# @@protoc_insertion_point(module_scope)
