# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/audio/AudioFocusStateEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/audio/AudioFocusStateEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/audio/AudioFocusStateEnum.proto\x12\x0foaa.proto.enums\"\xb7\x01\n\x0f\x41udioFocusState\"\xa3\x01\n\x04\x45num\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04GAIN\x10\x01\x12\x12\n\x0eGAIN_TRANSIENT\x10\x02\x12\x08\n\x04LOSS\x10\x03\x12\x1b\n\x17LOSS_TRANSIENT_CAN_DUCK\x10\x04\x12\x12\n\x0eLOSS_TRANSIENT\x10\x05\x12\x13\n\x0fGAIN_MEDIA_ONLY\x10\x06\x12 \n\x1cGAIN_TRANSIENT_GUIDANCE_ONLY\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.audio.AudioFocusStateEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFOCUSSTATE']._serialized_start=57
  _globals['_AUDIOFOCUSSTATE']._serialized_end=240
  _globals['_AUDIOFOCUSSTATE_ENUM']._serialized_start=77
  _globals['_AUDIOFOCUSSTATE_ENUM']._serialized_end=240
# @@protoc_insertion_point(module_scope)
