# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiSecurityResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiSecurityResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.wifi import WifiDirectConfigData_pb2 as oaa_dot_wifi_dot_WifiDirectConfigData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/wifi/WifiSecurityResponseMessage.proto\x12\x12oaa.proto.messages\x1a#oaa/wifi/WifiDirectConfigData.proto\"\xa9\x05\n\x14WifiSecurityResponse\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05\x62ssid\x18\x03 \x01(\t\x12L\n\rsecurity_mode\x18\x04 \x01(\x0e\x32\x35.oaa.proto.messages.WifiSecurityResponse.SecurityMode\x12S\n\x11\x61\x63\x63\x65ss_point_type\x18\x05 \x01(\x0e\x32\x38.oaa.proto.messages.WifiSecurityResponse.AccessPointType\x12<\n\x12wifi_direct_config\x18\x06 \x01(\x0b\x32 .oaa.proto.data.WifiDirectConfig\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x0f\n\x07gateway\x18\x08 \x01(\t\x12\x15\n\rprefix_length\x18\t \x01(\r\x12\x16\n\x0ehidden_network\x18\n \x01(\x08\x12\x11\n\tband_5ghz\x18\x0b \x01(\x08\x12\x12\n\nunknown_12\x18\x0c \x01(\t\x12\x12\n\nunknown_13\x18\r \x01(\x08\"\xca\x01\n\x0cSecurityMode\x12\x19\n\x15UNKNOWN_SECURITY_MODE\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06WEP_64\x10\x02\x12\x0b\n\x07WEP_128\x10\x03\x12\x10\n\x0cWPA_PERSONAL\x10\x04\x12\x11\n\rWPA2_PERSONAL\x10\x08\x12\x15\n\x11WPA_WPA2_PERSONAL\x10\x0c\x12\x12\n\x0eWPA_ENTERPRISE\x10\x14\x12\x13\n\x0fWPA2_ENTERPRISE\x10\x18\x12\x17\n\x13WPA_WPA2_ENTERPRISE\x10\x1c\"*\n\x0f\x41\x63\x63\x65ssPointType\x12\n\n\x06STATIC\x10\x00\x12\x0b\n\x07\x44YNAMIC\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiSecurityResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISECURITYRESPONSE']._serialized_start=104
  _globals['_WIFISECURITYRESPONSE']._serialized_end=785
  _globals['_WIFISECURITYRESPONSE_SECURITYMODE']._serialized_start=539
  _globals['_WIFISECURITYRESPONSE_SECURITYMODE']._serialized_end=741
  _globals['_WIFISECURITYRESPONSE_ACCESSPOINTTYPE']._serialized_start=743
  _globals['_WIFISECURITYRESPONSE_ACCESSPOINTTYPE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
