# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiConnectionRejectionMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiConnectionRejectionMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.wifi import WifiConnectionRejectionReasonEnum_pb2 as oaa_dot_wifi_dot_WifiConnectionRejectionReasonEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-oaa/wifi/WifiConnectionRejectionMessage.proto\x12\x12oaa.proto.messages\x1a\x30oaa/wifi/WifiConnectionRejectionReasonEnum.proto\"^\n\x17WifiConnectionRejection\x12\x43\n\x06reason\x18\x01 \x01(\x0e\x32\x33.oaa.proto.enums.WifiConnectionRejectionReason.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiConnectionRejectionMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICONNECTIONREJECTION']._serialized_start=119
  _globals['_WIFICONNECTIONREJECTION']._serialized_end=213
# @@protoc_insertion_point(module_scope)
