# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiInfoResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiInfoResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.wifi import WifiSecurityModeEnum_pb2 as oaa_dot_wifi_dot_WifiSecurityModeEnum__pb2
from oaa.wifi import WifiAccessPointTypeEnum_pb2 as oaa_dot_wifi_dot_WifiAccessPointTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/wifi/WifiInfoResponseMessage.proto\x12\x12oaa.proto.messages\x1a#oaa/wifi/WifiSecurityModeEnum.proto\x1a&oaa/wifi/WifiAccessPointTypeEnum.proto\"\xbe\x01\n\x10WifiInfoResponse\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\r\n\x05\x62ssid\x18\x02 \x01(\t\x12\x12\n\npassphrase\x18\x03 \x01(\t\x12=\n\rsecurity_mode\x18\x04 \x01(\x0e\x32&.oaa.proto.enums.WifiSecurityMode.Enum\x12:\n\x07\x61p_type\x18\x05 \x01(\x0e\x32).oaa.proto.enums.WifiAccessPointType.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiInfoResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIINFORESPONSE']._serialized_start=140
  _globals['_WIFIINFORESPONSE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
