# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiChannelTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiChannelTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/wifi/WifiChannelTypeEnum.proto\x12\x0foaa.proto.enums\"\x88\x01\n\x0fWifiChannelType\"u\n\x04\x45num\x12\x18\n\x14\x43HANNEL_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16\x43HANNEL_TYPE_5GHZ_ONLY\x10\x01\x12\x1b\n\x17\x43HANNEL_TYPE_24GHZ_ONLY\x10\x02\x12\x1a\n\x16\x43HANNEL_TYPE_DUAL_BAND\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiChannelTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICHANNELTYPE']._serialized_start=56
  _globals['_WIFICHANNELTYPE']._serialized_end=192
  _globals['_WIFICHANNELTYPE_ENUM']._serialized_start=75
  _globals['_WIFICHANNELTYPE_ENUM']._serialized_end=192
# @@protoc_insertion_point(module_scope)
