# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiVersionRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiVersionRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import PhoneCapabilitiesData_pb2 as oaa_dot_control_dot_PhoneCapabilitiesData__pb2
from oaa.common import FeatureFlagsData_pb2 as oaa_dot_common_dot_FeatureFlagsData__pb2
from oaa.wifi import WifiChannelTypeEnum_pb2 as oaa_dot_wifi_dot_WifiChannelTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/wifi/WifiVersionRequestMessage.proto\x12\x12oaa.proto.messages\x1a\'oaa/control/PhoneCapabilitiesData.proto\x1a!oaa/common/FeatureFlagsData.proto\x1a\"oaa/wifi/WifiChannelTypeEnum.proto\"\x93\x02\n\x12WifiVersionRequest\x12\x15\n\rmajor_version\x18\x01 \x01(\x05\x12\x15\n\rminor_version\x18\x02 \x01(\x05\x12\x46\n\x17wifi_channel_preference\x18\x03 \x01(\x0e\x32%.oaa.proto.enums.WifiChannelType.Enum\x12\x1a\n\x12supported_channels\x18\x04 \x03(\x05\x12/\n\x0b\x64\x65vice_info\x18\x05 \x01(\x0b\x32\x1a.oaa.proto.data.DeviceInfo\x12:\n\rfeature_flags\x18\x06 \x01(\x0b\x32#.oaa.proto.data.VersionFeatureFlags')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiVersionRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFIVERSIONREQUEST']._serialized_start=177
  _globals['_WIFIVERSIONREQUEST']._serialized_end=452
# @@protoc_insertion_point(module_scope)
