# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiSecurityModeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiSecurityModeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#oaa/wifi/WifiSecurityModeEnum.proto\x12\x0foaa.proto.enums\"\x82\x02\n\x10WifiSecurityMode\"\xed\x01\n\x04\x45num\x12\x19\n\x15UNKNOWN_SECURITY_MODE\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06WEP_64\x10\x02\x12\x0b\n\x07WEP_128\x10\x03\x12\x10\n\x0cWPA_PERSONAL\x10\x04\x12\x11\n\rWPA2_PERSONAL\x10\x08\x12\x15\n\x11WPA_WPA2_PERSONAL\x10\x0c\x12\x12\n\x0eWPA_ENTERPRISE\x10\x14\x12\x13\n\x0fWPA2_ENTERPRISE\x10\x18\x12\x17\n\x13WPA_WPA2_ENTERPRISE\x10\x1c\x12\x11\n\rWPA3_PERSONAL\x10 \x12\x16\n\x12WPA2_WPA3_PERSONAL\x10(')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiSecurityModeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISECURITYMODE']._serialized_start=57
  _globals['_WIFISECURITYMODE']._serialized_end=315
  _globals['_WIFISECURITYMODE_ENUM']._serialized_start=78
  _globals['_WIFISECURITYMODE_ENUM']._serialized_end=315
# @@protoc_insertion_point(module_scope)
