# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/wifi/WifiConnectionRejectionReasonEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/wifi/WifiConnectionRejectionReasonEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0oaa/wifi/WifiConnectionRejectionReasonEnum.proto\x12\x0foaa.proto.enums\"\x91\x01\n\x1dWifiConnectionRejectionReason\"p\n\x04\x45num\x12\x1c\n\x18REJECTION_REASON_UNKNOWN\x10\x00\x12 \n\x1cREJECTION_REASON_NOT_ALLOWED\x10\x01\x12(\n$REJECTION_REASON_INVALID_SETUP_TOKEN\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.wifi.WifiConnectionRejectionReasonEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICONNECTIONREJECTIONREASON']._serialized_start=70
  _globals['_WIFICONNECTIONREJECTIONREASON']._serialized_end=215
  _globals['_WIFICONNECTIONREJECTIONREASON_ENUM']._serialized_start=103
  _globals['_WIFICONNECTIONREJECTIONREASON_ENUM']._serialized_end=215
# @@protoc_insertion_point(module_scope)
