# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/BindingResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/BindingResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import StatusEnum_pb2 as oaa_dot_common_dot_StatusEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/control/BindingResponseMessage.proto\x12\x12oaa.proto.messages\x1a\x1boaa/common/StatusEnum.proto\"W\n\x0f\x42indingResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.oaa.proto.enums.Status.Enum\x12\x16\n\x0e\x61lready_paired\x18\x02 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.BindingResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINDINGRESPONSE']._serialized_start=93
  _globals['_BINDINGRESPONSE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
