# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/CapabilityData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/CapabilityData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n oaa/control/CapabilityData.proto\x12\x0eoaa.proto.data\"/\n\x0e\x43\x61pabilityFlag\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\x0e\x43\x61pabilityPair\x12\x0f\n\x07value_a\x18\x01 \x01(\x08\x12\x0f\n\x07value_b\x18\x02 \x01(\x08\"|\n\x0ePingConfigPair\x12\x34\n\x0bphone_to_hu\x18\x01 \x01(\x0b\x32\x1f.oaa.proto.data.PingConfigEntry\x12\x34\n\x0bhu_to_phone\x18\x02 \x01(\x0b\x32\x1f.oaa.proto.data.PingConfigEntry\":\n\x0fPingConfigEntry\x12\x12\n\ntimeout_ms\x18\x01 \x01(\x03\x12\x13\n\x0binterval_ms\x18\x02 \x01(\x05\"\xd9\x03\n\x0f\x43\x61pabilityEntry\x12\x15\n\rcapability_id\x18\x01 \x01(\r\x12\x17\n\x0f\x63\x61pability_name\x18\x02 \x01(\t\x12\x37\n\x0f\x63\x61pability_type\x18\x03 \x01(\x0e\x32\x1e.oaa.proto.data.CapabilityEnum\x12\x39\n\x0bvalue_msg_4\x18\x04 \x01(\x0b\x32\".oaa.proto.data.CapabilityValueMsgH\x00\x12\x39\n\x0bvalue_msg_5\x18\x05 \x01(\x0b\x32\".oaa.proto.data.CapabilityValueMsgH\x00\x12\x39\n\x0bvalue_msg_6\x18\x06 \x01(\x0b\x32\".oaa.proto.data.CapabilityValueMsgH\x00\x12\x39\n\x0bvalue_msg_7\x18\x07 \x01(\x0b\x32\".oaa.proto.data.CapabilityValueMsgH\x00\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x37\n\x0bsub_entries\x18\n \x03(\x0b\x32\".oaa.proto.data.CapabilityValueMsgB\x12\n\x10\x63\x61pability_value\"\x14\n\x12\x43\x61pabilityValueMsg*(\n\x0e\x43\x61pabilityEnum\x12\x16\n\x12\x43\x41PABILITY_UNKNOWN\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.CapabilityData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITYENUM']._serialized_start=837
  _globals['_CAPABILITYENUM']._serialized_end=877
  _globals['_CAPABILITYFLAG']._serialized_start=52
  _globals['_CAPABILITYFLAG']._serialized_end=99
  _globals['_CAPABILITYPAIR']._serialized_start=101
  _globals['_CAPABILITYPAIR']._serialized_end=151
  _globals['_PINGCONFIGPAIR']._serialized_start=153
  _globals['_PINGCONFIGPAIR']._serialized_end=277
  _globals['_PINGCONFIGENTRY']._serialized_start=279
  _globals['_PINGCONFIGENTRY']._serialized_end=337
  _globals['_CAPABILITYENTRY']._serialized_start=340
  _globals['_CAPABILITYENTRY']._serialized_end=813
  _globals['_CAPABILITYVALUEMSG']._serialized_start=815
  _globals['_CAPABILITYVALUEMSG']._serialized_end=835
# @@protoc_insertion_point(module_scope)
