# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ConnectedDevicesMessages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ConnectedDevicesMessages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/control/ConnectedDevicesMessages.proto\x12\x12oaa.proto.messages\"a\n\x0f\x43onnectedDevice\x12\x18\n\x0b\x64\x65vice_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tdevice_id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x0e\n\x0c_device_nameB\x0c\n\n_device_id\"\x1c\n\x1a\x43\x61rConnectedDevicesRequest\"\xaf\x01\n\x1b\x43\x61rConnectedDevicesResponse\x12>\n\x11\x63onnected_devices\x18\x01 \x03(\x0b\x32#.oaa.proto.messages.ConnectedDevice\x12\x18\n\x0bunsolicited\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x17\n\nfinal_list\x18\x03 \x01(\x08H\x01\x88\x01\x01\x42\x0e\n\x0c_unsolicitedB\r\n\x0b_final_list\"j\n\x11UserSwitchRequest\x12\x41\n\x0fselected_device\x18\x01 \x01(\x0b\x32#.oaa.proto.messages.ConnectedDeviceH\x00\x88\x01\x01\x42\x12\n\x10_selected_device\"\xb1\x01\n\x12UserSwitchResponse\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32$.oaa.proto.messages.UserSwitchStatusH\x00\x88\x01\x01\x12\x41\n\x0fselected_device\x18\x02 \x01(\x0b\x32#.oaa.proto.messages.ConnectedDeviceH\x01\x88\x01\x01\x42\t\n\x07_statusB\x12\n\x10_selected_device*\xaf\x03\n\x10UserSwitchStatus\x12\x12\n\x0eUSER_SWITCH_OK\x10\x00\x12*\n&USER_SWITCH_ERROR_NO_RFCOMM_CONNECTION\x10\x01\x12,\n(USER_SWITCH_ERROR_BT_CLOSED_BEFORE_START\x10\x02\x12+\n\'USER_SWITCH_ERROR_BT_CLOSED_AFTER_START\x10\x03\x12\x33\n/USER_SWITCH_ERROR_INCOMPATIBLE_PROTOCOL_VERSION\x10\x04\x12\x32\n.USER_SWITCH_ERROR_PHONE_UNABLE_TO_CONNECT_WIFI\x10\x05\x12&\n\"USER_SWITCH_ERROR_MULTIPLE_REQUEST\x10\x06\x12!\n\x1dUSER_SWITCH_ERROR_HU_INTERNAL\x10\x07\x12%\n!USER_SWITCH_ERROR_INVALID_REQUEST\x10\x08\x12%\n!USER_SWITCH_ERROR_REQUEST_TIMEOUT\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ConnectedDevicesMessages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSWITCHSTATUS']._serialized_start=662
  _globals['_USERSWITCHSTATUS']._serialized_end=1093
  _globals['_CONNECTEDDEVICE']._serialized_start=66
  _globals['_CONNECTEDDEVICE']._serialized_end=163
  _globals['_CARCONNECTEDDEVICESREQUEST']._serialized_start=165
  _globals['_CARCONNECTEDDEVICESREQUEST']._serialized_end=193
  _globals['_CARCONNECTEDDEVICESRESPONSE']._serialized_start=196
  _globals['_CARCONNECTEDDEVICESRESPONSE']._serialized_end=371
  _globals['_USERSWITCHREQUEST']._serialized_start=373
  _globals['_USERSWITCHREQUEST']._serialized_end=479
  _globals['_USERSWITCHRESPONSE']._serialized_start=482
  _globals['_USERSWITCHRESPONSE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
