# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/PhoneCapabilitiesData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/PhoneCapabilitiesData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/control/PhoneCapabilitiesData.proto\x12\x0eoaa.proto.data\"\xbe\x01\n\nDeviceInfo\x12\x14\n\x0cmanufacturer\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x17\n\x0f\x61ndroid_version\x18\x03 \x01(\t\x12\x19\n\x11\x62uild_fingerprint\x18\x04 \x01(\t\x12\x0f\n\x07\x66ield_5\x18\x05 \x01(\t\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\t\x12\x0f\n\x07\x66ield_7\x18\x07 \x01(\t\x12\x0f\n\x07\x66ield_8\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\t \x01(\x05\"\xb7\x01\n\x15PhoneConnectionConfig\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\r\n\x05\x62ssid\x18\x02 \x01(\t\x12\x12\n\npassphrase\x18\x03 \x01(\t\x12\x37\n\rsecurity_mode\x18\x04 \x01(\x0e\x32 .oaa.proto.data.WifiSecurityMode\x12\x34\n\x07\x61p_type\x18\x05 \x01(\x0e\x32#.oaa.proto.data.WifiAccessPointType*\x93\x03\n\x10WifiSecurityMode\x12\x19\n\x15WIFI_SECURITY_UNKNOWN\x10\x00\x12\x16\n\x12WIFI_SECURITY_OPEN\x10\x01\x12\x18\n\x14WIFI_SECURITY_WEP_64\x10\x02\x12\x19\n\x15WIFI_SECURITY_WEP_128\x10\x03\x12\x1e\n\x1aWIFI_SECURITY_WPA_PERSONAL\x10\x04\x12\x1f\n\x1bWIFI_SECURITY_WPA2_PERSONAL\x10\x08\x12#\n\x1fWIFI_SECURITY_WPA_WPA2_PERSONAL\x10\x0c\x12 \n\x1cWIFI_SECURITY_WPA_ENTERPRISE\x10\x14\x12!\n\x1dWIFI_SECURITY_WPA2_ENTERPRISE\x10\x18\x12%\n!WIFI_SECURITY_WPA_WPA2_ENTERPRISE\x10\x1c\x12\x1f\n\x1bWIFI_SECURITY_WPA3_PERSONAL\x10 \x12$\n WIFI_SECURITY_WPA2_WPA3_PERSONAL\x10(*>\n\x13WifiAccessPointType\x12\x12\n\x0eWIFI_AP_STATIC\x10\x00\x12\x13\n\x0fWIFI_AP_DYNAMIC\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.PhoneCapabilitiesData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISECURITYMODE']._serialized_start=439
  _globals['_WIFISECURITYMODE']._serialized_end=842
  _globals['_WIFIACCESSPOINTTYPE']._serialized_start=844
  _globals['_WIFIACCESSPOINTTYPE']._serialized_end=906
  _globals['_DEVICEINFO']._serialized_start=60
  _globals['_DEVICEINFO']._serialized_end=250
  _globals['_PHONECONNECTIONCONFIG']._serialized_start=253
  _globals['_PHONECONNECTIONCONFIG']._serialized_end=436
# @@protoc_insertion_point(module_scope)
