# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/RadioChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/RadioChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.radio import RadioBandTypeEnum_pb2 as oaa_dot_radio_dot_RadioBandTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/control/RadioChannelData.proto\x12\x0eoaa.proto.data\x1a!oaa/radio/RadioBandTypeEnum.proto\"R\n\x12RadioChannelConfig\x12\x11\n\tconfig_id\x18\x01 \x01(\x05\x12)\n\x05\x62\x61nds\x18\x02 \x01(\x0b\x32\x1a.oaa.proto.data.RadioBands\"<\n\nRadioBands\x12.\n\x06groups\x18\x01 \x03(\x0b\x32\x1e.oaa.proto.data.RadioBandGroup\"}\n\x0eRadioBandGroup\x12\x37\n\nband_types\x18\x01 \x03(\x0e\x32#.oaa.proto.enums.RadioBandType.Enum\x12\x18\n\x10hide_empty_group\x18\x02 \x01(\x08\x12\x18\n\x10\x62\x61nd_scan_action\x18\x03 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.RadioChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADIOCHANNELCONFIG']._serialized_start=89
  _globals['_RADIOCHANNELCONFIG']._serialized_end=171
  _globals['_RADIOBANDS']._serialized_start=173
  _globals['_RADIOBANDS']._serialized_end=233
  _globals['_RADIOBANDGROUP']._serialized_start=235
  _globals['_RADIOBANDGROUP']._serialized_end=360
# @@protoc_insertion_point(module_scope)
