# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ServiceDiscoveryUpdateMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ServiceDiscoveryUpdateMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import ChannelDescriptorData_pb2 as oaa_dot_control_dot_ChannelDescriptorData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/oaa/control/ServiceDiscoveryUpdateMessage.proto\x12\x12oaa.proto.messages\x1a\'oaa/control/ChannelDescriptorData.proto\"O\n\x16ServiceDiscoveryUpdate\x12\x35\n\ndescriptor\x18\x01 \x01(\x0b\x32!.oaa.proto.data.ChannelDescriptor')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ServiceDiscoveryUpdateMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEDISCOVERYUPDATE']._serialized_start=112
  _globals['_SERVICEDISCOVERYUPDATE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
