# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ShutdownRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ShutdownRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import ShutdownReasonEnum_pb2 as oaa_dot_control_dot_ShutdownReasonEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/control/ShutdownRequestMessage.proto\x12\x12oaa.proto.messages\x1a$oaa/control/ShutdownReasonEnum.proto\"G\n\x0fShutdownRequest\x12\x34\n\x06reason\x18\x01 \x02(\x0e\x32$.oaa.proto.enums.ShutdownReason.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ShutdownRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHUTDOWNREQUEST']._serialized_start=102
  _globals['_SHUTDOWNREQUEST']._serialized_end=173
# @@protoc_insertion_point(module_scope)
