# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/VoiceSessionRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/VoiceSessionRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,oaa/control/VoiceSessionRequestMessage.proto\x12\x12oaa.proto.messages\"Q\n\x13VoiceSessionRequest\x12:\n\x0csession_type\x18\x01 \x01(\x0e\x32$.oaa.proto.messages.VoiceSessionType*C\n\x10VoiceSessionType\x12\x17\n\x13VOICE_SESSION_START\x10\x01\x12\x16\n\x12VOICE_SESSION_STOP\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.VoiceSessionRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICESESSIONTYPE']._serialized_start=151
  _globals['_VOICESESSIONTYPE']._serialized_end=218
  _globals['_VOICESESSIONREQUEST']._serialized_start=68
  _globals['_VOICESESSIONREQUEST']._serialized_end=149
# @@protoc_insertion_point(module_scope)
