# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/DrivingStatusEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/DrivingStatusEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/sensor/DrivingStatusEnum.proto\x12\x0foaa.proto.enums\"\x9f\x01\n\rDrivingStatus\"\x8d\x01\n\x04\x45num\x12\x10\n\x0cUNRESTRICTED\x10\x00\x12\x0c\n\x08NO_VIDEO\x10\x01\x12\x15\n\x11NO_KEYBOARD_INPUT\x10\x02\x12\x12\n\x0eNO_VOICE_INPUT\x10\x04\x12\r\n\tNO_CONFIG\x10\x08\x12\x15\n\x11LIMIT_MESSAGE_LEN\x10\x10\x12\x14\n\x10\x46ULLY_RESTRICTED\x10\x1f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.DrivingStatusEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVINGSTATUS']._serialized_start=56
  _globals['_DRIVINGSTATUS']._serialized_end=215
  _globals['_DRIVINGSTATUS_ENUM']._serialized_start=74
  _globals['_DRIVINGSTATUS_ENUM']._serialized_end=215
# @@protoc_insertion_point(module_scope)
