# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/EVConnectorTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/EVConnectorTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$oaa/sensor/EVConnectorTypeEnum.proto\x12\x0foaa.proto.enums\"\xcd\x01\n\x0f\x45VConnectorType\"\xb9\x01\n\x04\x45num\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05J1772\x10\x01\x12\x0c\n\x08MENNEKES\x10\x02\x12\x0b\n\x07\x43HADEMO\x10\x03\x12\x0b\n\x07\x43OMBO_1\x10\x04\x12\x0b\n\x07\x43OMBO_2\x10\x05\x12\x12\n\x0eTESLA_ROADSTER\x10\x06\x12\x0e\n\nTESLA_HPWC\x10\x07\x12\x16\n\x12TESLA_SUPERCHARGER\x10\x08\x12\x07\n\x03GBT\x10\t\x12\n\n\x06GBT_DC\x10\n\x12\t\n\x05LECCS\x10\x0b\x12\x08\n\x04NACS\x10\x0e')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.EVConnectorTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVCONNECTORTYPE']._serialized_start=58
  _globals['_EVCONNECTORTYPE']._serialized_end=263
  _globals['_EVCONNECTORTYPE_ENUM']._serialized_start=78
  _globals['_EVCONNECTORTYPE_ENUM']._serialized_end=263
# @@protoc_insertion_point(module_scope)
