# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/FuelTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/FuelTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1doaa/sensor/FuelTypeEnum.proto\x12\x0foaa.proto.enums\"\xb0\x01\n\x08\x46uelType\"\xa3\x01\n\x04\x45num\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08UNLEADED\x10\x01\x12\n\n\x06LEADED\x10\x02\x12\x0c\n\x08\x44IESEL_1\x10\x03\x12\x0c\n\x08\x44IESEL_2\x10\x04\x12\r\n\tBIODIESEL\x10\x05\x12\x07\n\x03\x45\x38\x35\x10\x06\x12\x07\n\x03LPG\x10\x07\x12\x07\n\x03\x43NG\x10\x08\x12\x07\n\x03LNG\x10\t\x12\x0c\n\x08\x45LECTRIC\x10\n\x12\x0c\n\x08HYDROGEN\x10\x0b\x12\t\n\x05OTHER\x10\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.FuelTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUELTYPE']._serialized_start=51
  _globals['_FUELTYPE']._serialized_end=227
  _globals['_FUELTYPE_ENUM']._serialized_start=64
  _globals['_FUELTYPE_ENUM']._serialized_end=227
# @@protoc_insertion_point(module_scope)
