# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/GpsSatelliteData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/GpsSatelliteData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!oaa/sensor/GpsSatelliteData.proto\x12\x0eoaa.proto.data\"`\n\x10GpsSatelliteInfo\x12\x0b\n\x03prn\x18\x01 \x02(\x05\x12\x0b\n\x03snr\x18\x02 \x02(\x05\x12\x0e\n\x06in_use\x18\x03 \x02(\x08\x12\x0f\n\x07\x61zimuth\x18\x04 \x01(\x05\x12\x11\n\televation\x18\x05 \x01(\x05\"z\n\x10GpsSatelliteData\x12\x17\n\x0fsatellite_count\x18\x01 \x02(\x05\x12\x17\n\x0fsatellites_used\x18\x02 \x01(\x05\x12\x34\n\nsatellites\x18\x03 \x03(\x0b\x32 .oaa.proto.data.GpsSatelliteInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.GpsSatelliteData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPSSATELLITEINFO']._serialized_start=53
  _globals['_GPSSATELLITEINFO']._serialized_end=149
  _globals['_GPSSATELLITEDATA']._serialized_start=151
  _globals['_GPSSATELLITEDATA']._serialized_end=273
# @@protoc_insertion_point(module_scope)
