# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/SensorStartRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/SensorStartRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.sensor import SensorTypeEnum_pb2 as oaa_dot_sensor_dot_SensorTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/sensor/SensorStartRequestMessage.proto\x12\x12oaa.proto.messages\x1a\x1foaa/sensor/SensorTypeEnum.proto\"l\n\x19SensorStartRequestMessage\x12\x35\n\x0bsensor_type\x18\x01 \x01(\x0e\x32 .oaa.proto.enums.SensorType.Enum\x12\x18\n\x10refresh_interval\x18\x02 \x01(\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.SensorStartRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORSTARTREQUESTMESSAGE']._serialized_start=99
  _globals['_SENSORSTARTREQUESTMESSAGE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
