# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/mediabrowser/MediaBrowserMessageIdsEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/mediabrowser/MediaBrowserMessageIdsEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1oaa/mediabrowser/MediaBrowserMessageIdsEnum.proto\x12\x0foaa.proto.enums\"\xae\x01\n\x15MediaBrowserMessageId\"\x94\x01\n\x04\x45num\x12\x15\n\x0fMEDIA_ROOT_NODE\x10\x81\x80\x02\x12\x17\n\x11MEDIA_SOURCE_NODE\x10\x82\x80\x02\x12\x15\n\x0fMEDIA_LIST_NODE\x10\x83\x80\x02\x12\x15\n\x0fMEDIA_SONG_NODE\x10\x84\x80\x02\x12\x14\n\x0eMEDIA_GET_NODE\x10\x85\x80\x02\x12\x18\n\x12MEDIA_BROWSE_INPUT\x10\x86\x80\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.mediabrowser.MediaBrowserMessageIdsEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIABROWSERMESSAGEID']._serialized_start=71
  _globals['_MEDIABROWSERMESSAGEID']._serialized_end=245
  _globals['_MEDIABROWSERMESSAGEID_ENUM']._serialized_start=97
  _globals['_MEDIABROWSERMESSAGEID_ENUM']._serialized_end=245
# @@protoc_insertion_point(module_scope)
