# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/LocationCharacterizationEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/LocationCharacterizationEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-oaa/common/LocationCharacterizationEnum.proto\x12\x0foaa.proto.enums*\xb4\x02\n\x18LocationCharacterization\x12\x1c\n\x18LOCATION_PRIOR_LOCATIONS\x10\x01\x12\x1d\n\x19LOCATION_GYROSCOPE_FUSION\x10\x02\x12!\n\x1dLOCATION_ACCELEROMETER_FUSION\x10\x04\x12\x1b\n\x17LOCATION_COMPASS_FUSION\x10\x08\x12\x1f\n\x1bLOCATION_WHEEL_SPEED_FUSION\x10\x10\x12\"\n\x1eLOCATION_STEERING_ANGLE_FUSION\x10 \x12\x1d\n\x19LOCATION_CAR_SPEED_FUSION\x10@\x12\x1b\n\x16LOCATION_DEAD_RECKONED\x10\x80\x01\x12\x1a\n\x15LOCATION_RAW_GPS_ONLY\x10\x80\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.LocationCharacterizationEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONCHARACTERIZATION']._serialized_start=67
  _globals['_LOCATIONCHARACTERIZATION']._serialized_end=375
# @@protoc_insertion_point(module_scope)
