# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/SessionConfigurationEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/SessionConfigurationEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)oaa/common/SessionConfigurationEnum.proto\x12\x0foaa.proto.enums*\xb8\x01\n\x14SessionConfiguration\x12 \n\x1cSESSION_UI_CONFIG_HIDE_CLOCK\x10\x01\x12\'\n#SESSION_UI_CONFIG_HIDE_PHONE_SIGNAL\x10\x02\x12(\n$SESSION_UI_CONFIG_HIDE_BATTERY_LEVEL\x10\x04\x12+\n\'SESSION_CAN_PLAY_NATIVE_MEDIA_DURING_VR\x10\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.SessionConfigurationEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONCONFIGURATION']._serialized_start=63
  _globals['_SESSIONCONFIGURATION']._serialized_end=247
# @@protoc_insertion_point(module_scope)
