# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/bluetooth/BluetoothChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/bluetooth/BluetoothChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.bluetooth import BluetoothPairingMethodEnum_pb2 as oaa_dot_bluetooth_dot_BluetoothPairingMethodEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/bluetooth/BluetoothChannelData.proto\x12\x0eoaa.proto.data\x1a.oaa/bluetooth/BluetoothPairingMethodEnum.proto\"\x80\x01\n\x10\x42luetoothChannel\x12\x17\n\x0f\x61\x64\x61pter_address\x18\x01 \x02(\t\x12S\n\x19supported_pairing_methods\x18\x02 \x03(\x0e\x32,.oaa.proto.enums.BluetoothPairingMethod.EnumB\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.bluetooth.BluetoothChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHCHANNEL'].fields_by_name['supported_pairing_methods']._loaded_options = None
  _globals['_BLUETOOTHCHANNEL'].fields_by_name['supported_pairing_methods']._serialized_options = b'\020\001'
  _globals['_BLUETOOTHCHANNEL']._serialized_start=109
  _globals['_BLUETOOTHCHANNEL']._serialized_end=237
# @@protoc_insertion_point(module_scope)
