# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/bluetooth/BluetoothChannelMessageIdsEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/bluetooth/BluetoothChannelMessageIdsEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2oaa/bluetooth/BluetoothChannelMessageIdsEnum.proto\x12\roaa.proto.ids\"~\n\x17\x42luetoothChannelMessage\"c\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x15\n\x0fPAIRING_REQUEST\x10\x81\x80\x02\x12\x16\n\x10PAIRING_RESPONSE\x10\x82\x80\x02\x12\x0f\n\tAUTH_DATA\x10\x83\x80\x02\x12\x11\n\x0b\x41UTH_RESULT\x10\x84\x80\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.bluetooth.BluetoothChannelMessageIdsEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLUETOOTHCHANNELMESSAGE']._serialized_start=69
  _globals['_BLUETOOTHCHANNELMESSAGE']._serialized_end=195
  _globals['_BLUETOOTHCHANNELMESSAGE_ENUM']._serialized_start=96
  _globals['_BLUETOOTHCHANNELMESSAGE_ENUM']._serialized_end=195
# @@protoc_insertion_point(module_scope)
