# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/media/CarLocalMediaPlaybackStatusMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/media/CarLocalMediaPlaybackStatusMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2oaa/media/CarLocalMediaPlaybackStatusMessage.proto\x12\x12oaa.proto.messages\"\xd8\x01\n\x1b\x43\x61rLocalMediaPlaybackStatus\x12\x46\n\x0eplayback_state\x18\x01 \x01(\x0e\x32..oaa.proto.messages.CarLocalMediaPlaybackState\x12\x14\n\x0cmedia_source\x18\x02 \x01(\t\x12\x19\n\x11playback_position\x18\x03 \x01(\x05\x12@\n\x07\x61\x63tions\x18\x04 \x03(\x0e\x32/.oaa.proto.messages.CarLocalMediaPlaybackAction*\xbb\x01\n\x1a\x43\x61rLocalMediaPlaybackState\x12\x1e\n\x1a\x43\x41R_LOCAL_PLAYBACK_STOPPED\x10\x01\x12\x1e\n\x1a\x43\x41R_LOCAL_PLAYBACK_PLAYING\x10\x02\x12\x1d\n\x19\x43\x41R_LOCAL_PLAYBACK_PAUSED\x10\x03\x12\x1c\n\x18\x43\x41R_LOCAL_PLAYBACK_ERROR\x10\x04\x12 \n\x1c\x43\x41R_LOCAL_PLAYBACK_UNKNOWN_5\x10\x05*\xd1\x01\n\x1b\x43\x61rLocalMediaPlaybackAction\x12!\n\x1d\x43\x41R_LOCAL_MEDIA_PLAYBACK_PLAY\x10\x00\x12\"\n\x1e\x43\x41R_LOCAL_MEDIA_PLAYBACK_PAUSE\x10\x01\x12%\n!CAR_LOCAL_MEDIA_PLAYBACK_PREVIOUS\x10\x02\x12!\n\x1d\x43\x41R_LOCAL_MEDIA_PLAYBACK_NEXT\x10\x03\x12!\n\x1d\x43\x41R_LOCAL_MEDIA_PLAYBACK_STOP\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.media.CarLocalMediaPlaybackStatusMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARLOCALMEDIAPLAYBACKSTATE']._serialized_start=294
  _globals['_CARLOCALMEDIAPLAYBACKSTATE']._serialized_end=481
  _globals['_CARLOCALMEDIAPLAYBACKACTION']._serialized_start=484
  _globals['_CARLOCALMEDIAPLAYBACKACTION']._serialized_end=693
  _globals['_CARLOCALMEDIAPLAYBACKSTATUS']._serialized_start=75
  _globals['_CARLOCALMEDIAPLAYBACKSTATUS']._serialized_end=291
# @@protoc_insertion_point(module_scope)
