# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/media/CarLocalMediaPlaybackRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/media/CarLocalMediaPlaybackRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.media import CarLocalMediaPlaybackStatusMessage_pb2 as oaa_dot_media_dot_CarLocalMediaPlaybackStatusMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3oaa/media/CarLocalMediaPlaybackRequestMessage.proto\x12\x12oaa.proto.messages\x1a\x32oaa/media/CarLocalMediaPlaybackStatusMessage.proto\"_\n\x1c\x43\x61rLocalMediaPlaybackRequest\x12?\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32/.oaa.proto.messages.CarLocalMediaPlaybackAction')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.media.CarLocalMediaPlaybackRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARLOCALMEDIAPLAYBACKREQUEST']._serialized_start=127
  _globals['_CARLOCALMEDIAPLAYBACKREQUEST']._serialized_end=222
# @@protoc_insertion_point(module_scope)
