# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/media/MediaPlaybackStatusMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/media/MediaPlaybackStatusMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/media/MediaPlaybackStatusMessage.proto\x12\x12oaa.proto.messages\"\xb3\x01\n\x13MediaPlaybackStatus\x12\x39\n\x0eplayback_state\x18\x01 \x01(\x0e\x32!.oaa.proto.messages.PlaybackState\x12\x12\n\nsource_app\x18\x02 \x01(\t\x12\x18\n\x10position_seconds\x18\x03 \x01(\r\x12\x0f\n\x07shuffle\x18\x04 \x01(\x08\x12\x0e\n\x06repeat\x18\x05 \x01(\x08\x12\x12\n\nrepeat_one\x18\x06 \x01(\x08*\x98\x01\n\rPlaybackState\x12\x1a\n\x16PLAYBACK_STATE_UNKNOWN\x10\x00\x12\x1a\n\x16PLAYBACK_STATE_STOPPED\x10\x01\x12\x1a\n\x16PLAYBACK_STATE_PLAYING\x10\x02\x12\x19\n\x15PLAYBACK_STATE_PAUSED\x10\x03\x12\x18\n\x14PLAYBACK_STATE_ERROR\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.media.MediaPlaybackStatusMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYBACKSTATE']._serialized_start=249
  _globals['_PLAYBACKSTATE']._serialized_end=401
  _globals['_MEDIAPLAYBACKSTATUS']._serialized_start=67
  _globals['_MEDIAPLAYBACKSTATUS']._serialized_end=246
# @@protoc_insertion_point(module_scope)
