# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/media/MediaPlaybackCommandMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/media/MediaPlaybackCommandMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+oaa/media/MediaPlaybackCommandMessage.proto\x12\x12oaa.proto.messages\"P\n\x14MediaPlaybackCommand\x12\x38\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\'.oaa.proto.messages.PlaybackCommandType*l\n\x13PlaybackCommandType\x12\x1c\n\x18PLAYBACK_COMMAND_UNKNOWN\x10\x00\x12\x1a\n\x16PLAYBACK_COMMAND_PAUSE\x10\x01\x12\x1b\n\x17PLAYBACK_COMMAND_RESUME\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.media.MediaPlaybackCommandMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYBACKCOMMANDTYPE']._serialized_start=149
  _globals['_PLAYBACKCOMMANDTYPE']._serialized_end=257
  _globals['_MEDIAPLAYBACKCOMMAND']._serialized_start=67
  _globals['_MEDIAPLAYBACKCOMMAND']._serialized_end=147
# @@protoc_insertion_point(module_scope)
