# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/media/MediaPlaybackStatusEventMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/media/MediaPlaybackStatusEventMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/oaa/media/MediaPlaybackStatusEventMessage.proto\x12\x12oaa.proto.messages\"`\n\x18MediaPlaybackStatusEvent\x12\x44\n\nevent_type\x18\x01 \x02(\x0e\x32\x30.oaa.proto.messages.MediaPlaybackStatusEventType*\xd1\x01\n\x1cMediaPlaybackStatusEventType\x12\x17\n\x13MEDIA_EVENT_UNKNOWN\x10\x00\x12\x12\n\x0eMEDIA_EVENT_UP\x10\x01\x12\x14\n\x10MEDIA_EVENT_DOWN\x10\x02\x12\x14\n\x10MEDIA_EVENT_LEFT\x10\x03\x12\x15\n\x11MEDIA_EVENT_RIGHT\x10\x04\x12\x15\n\x11MEDIA_EVENT_ENTER\x10\x05\x12\x14\n\x10MEDIA_EVENT_BACK\x10\x06\x12\x14\n\x10MEDIA_EVENT_CALL\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.media.MediaPlaybackStatusEventMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIAPLAYBACKSTATUSEVENTTYPE']._serialized_start=170
  _globals['_MEDIAPLAYBACKSTATUSEVENTTYPE']._serialized_end=379
  _globals['_MEDIAPLAYBACKSTATUSEVENT']._serialized_start=71
  _globals['_MEDIAPLAYBACKSTATUSEVENT']._serialized_end=167
# @@protoc_insertion_point(module_scope)
