# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/AssistantFeatureFlagsData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/AssistantFeatureFlagsData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/common/AssistantFeatureFlagsData.proto\x12\x0eoaa.proto.data\"\x83\x03\n\x15\x41ssistantFeatureFlags\x12\x1b\n\x13\x61ssistant_available\x18\x01 \x01(\x08\x12\x15\n\rvoice_trigger\x18\x02 \x01(\x08\x12\x1b\n\x13\x61ssistant_shortcuts\x18\x03 \x01(\x08\x12\x1e\n\x16\x63ontinued_conversation\x18\x04 \x01(\x08\x12\x18\n\x10\x64\x65vice_assistant\x18\x05 \x01(\x08\x12\x1f\n\x17\x61ssistant_on_lockscreen\x18\x06 \x01(\x08\x12\x15\n\rsmart_display\x18\x07 \x01(\x08\x12\x1b\n\x13routine_suggestions\x18\x08 \x01(\x08\x12\x18\n\x10interpreter_mode\x18\t \x01(\x08\x12\x13\n\x0bmulti_modal\x18\n \x01(\x08\x12\x18\n\x10settings_support\x18\x0b \x01(\x08\x12\x10\n\x08\x66ield_12\x18\x0c \x01(\x08\x12\x1d\n\x15proactive_suggestions\x18\r \x01(\x08\x12\x10\n\x08\x66ield_14\x18\x0e \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.AssistantFeatureFlagsData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSISTANTFEATUREFLAGS']._serialized_start=63
  _globals['_ASSISTANTFEATUREFLAGS']._serialized_end=450
# @@protoc_insertion_point(module_scope)
