# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/ChannelErrorCodeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/ChannelErrorCodeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%oaa/common/ChannelErrorCodeEnum.proto\x12\x0foaa.proto.enums\"\xdd\x06\n\x10\x43hannelErrorCode\"\xc8\x06\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x1c\n\x18INVALID_MESSAGE_RECEIVED\x10\x64\x12\x1d\n\x19\x43\x41R_DID_NOT_SEND_ALL_ACKS\x10\x66\x12\x1b\n\x17\x43\x41LLBACK_QUEUE_OVERFLOW\x10g\x12&\n\"RECEIVED_ACK_WITH_WRONG_SESSION_ID\x10h\x12\x1c\n\x17\x43HANNEL_CLOSE_REQUESTED\x10\xc8\x01\x12)\n$CHANNEL_CLOSED_DUE_TO_PROTOCOL_ERROR\x10\xc9\x01\x12\x31\n,TRIED_TO_SEND_CODEC_CONFIG_WHILE_NOT_STARTED\x10\xac\x02\x12)\n$TRIED_TO_SEND_DATA_WHILE_NOT_STARTED\x10\xad\x02\x12\x33\n.TRIED_TO_SEND_DATA_WHILE_CODEC_CONFIG_NOT_SENT\x10\xae\x02\x12\x1f\n\x1a\x41UDIO_CAPTURE_START_FAILED\x10\xe8\x07\x12\x1e\n\x19\x41UDIO_CAPTURE_STOP_FAILED\x10\xe9\x07\x12 \n\x1b\x41UDIO_PLAYBACK_START_FAILED\x10\xea\x07\x12\x1f\n\x1a\x41UDIO_PLAYBACK_STOP_FAILED\x10\xeb\x07\x12#\n\x1e\x41UDIO_BOTTOM_HALF_START_FAILED\x10\xec\x07\x12\"\n\x1d\x41UDIO_BOTTOM_HALF_STOP_FAILED\x10\xed\x07\x12.\n)AUDIO_STREAMING_REQUEST_CANCELLED_SILENCE\x10\xf0\x07\x12\x1e\n\x19\x41UDIO_HANDLE_FOCUS_CHANGE\x10\xcc\x08\x12!\n\x1c\x41UDIO_FOCUS_CHANGE_TIMED_OUT\x10\xcd\x08\x12\x1d\n\x18VIDEO_CODEC_START_FAILED\x10\xd0\x0f\x12\x1c\n\x17VIDEO_CODEC_STOP_FAILED\x10\xd1\x0f\x12\x1d\n\x18VIDEO_CODEC_FLUSH_FAILED\x10\xd2\x0f\x12\x1c\n\x17VIDEO_SURFACE_DESTROYED\x10\xb4\x10\x12\x1e\n\x19VIDEO_RENDER_THREAD_ERROR\x10\x98\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.ChannelErrorCodeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELERRORCODE']._serialized_start=59
  _globals['_CHANNELERRORCODE']._serialized_end=920
  _globals['_CHANNELERRORCODE_ENUM']._serialized_start=80
  _globals['_CHANNELERRORCODE_ENUM']._serialized_end=920
# @@protoc_insertion_point(module_scope)
