# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/ChannelTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/ChannelTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n oaa/common/ChannelTypeEnum.proto\x12\x0foaa.proto.enums\"\xbe\x03\n\x0b\x43hannelType\"\xae\x03\n\x04\x45num\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43ONTROL\x10\x01\x12\x0e\n\nVIDEO_SINK\x10\x02\x12\x17\n\x13\x41UDIO_SINK_GUIDANCE\x10\x03\x12\x15\n\x11\x41UDIO_SINK_SYSTEM\x10\x04\x12\x14\n\x10\x41UDIO_SINK_MEDIA\x10\x05\x12\x10\n\x0c\x41UDIO_SOURCE\x10\x06\x12\x11\n\rSENSOR_SOURCE\x10\x07\x12\x10\n\x0cINPUT_SOURCE\x10\x08\x12\r\n\tBLUETOOTH\x10\t\x12\x15\n\x11NAVIGATION_STATUS\x10\n\x12\x19\n\x15MEDIA_PLAYBACK_STATUS\x10\x0b\x12\x11\n\rMEDIA_BROWSER\x10\x0c\x12\x10\n\x0cPHONE_STATUS\x10\r\x12\x10\n\x0cNOTIFICATION\x10\x0e\x12\t\n\x05RADIO\x10\x0f\x12\x14\n\x10VENDOR_EXTENSION\x10\x10\x12\x13\n\x0fWIFI_PROJECTION\x10\x11\x12\x12\n\x0eWIFI_DISCOVERY\x10\x12\x12\x0f\n\x0b\x43\x41R_CONTROL\x10\x13\x12\x13\n\x0f\x43\x41R_LOCAL_MEDIA\x10\x14\x12\x17\n\x13\x42UFFERED_MEDIA_SINK\x10\x15\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.ChannelTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELTYPE']._serialized_start=54
  _globals['_CHANNELTYPE']._serialized_end=500
  _globals['_CHANNELTYPE_ENUM']._serialized_start=70
  _globals['_CHANNELTYPE_ENUM']._serialized_end=500
# @@protoc_insertion_point(module_scope)
