# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/ConnectionStateEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/ConnectionStateEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$oaa/common/ConnectionStateEnum.proto\x12\x0foaa.proto.enums\"\x92\x02\n\x0f\x43onnectionState\"\xfe\x01\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x1b\n\x17WAIT_FOR_CAR_CONNECTION\x10\x01\x12\x1b\n\x17\x43HECK_COUNTRY_WHITELIST\x10\x02\x12\x19\n\x15\x43HECK_PHONE_BLACKLIST\x10\x03\x12\x1c\n\x18\x41UTHORIZE_CAR_CONNECTION\x10\x04\x12\x0e\n\nCAR_MOVING\x10\t\x12\x0e\n\nSETUP_DONE\x10\x0c\x12\x15\n\x11\x43HECK_PERMISSIONS\x10\r\x12\x0f\n\x0bLOCK_SCREEN\x10\x0f\x12\x1e\n\x1aGH_WAIT_FOR_CAR_CONNECTION\x10\x10\x12\x11\n\rGH_SETUP_DONE\x10\x1e\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.ConnectionStateEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTIONSTATE']._serialized_start=58
  _globals['_CONNECTIONSTATE']._serialized_end=332
  _globals['_CONNECTIONSTATE_ENUM']._serialized_start=78
  _globals['_CONNECTIONSTATE_ENUM']._serialized_end=332
# @@protoc_insertion_point(module_scope)
