# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/DisconnectReasonEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/DisconnectReasonEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%oaa/common/DisconnectReasonEnum.proto\x12\x0foaa.proto.enums\"\xed\x02\n\x10\x44isconnectReason\"\xd8\x02\n\x04\x45num\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x14INCOMPATIBLE_VERSION\x10\x01\x12\x17\n\x13WRONG_CONFIGURATION\x10\x02\x12\x0c\n\x08IO_ERROR\x10\x03\x12\x1b\n\x17\x42YEBYE_REQUESTED_BY_CAR\x10\x04\x12\x1c\n\x18\x42YEBYE_REQUESTED_BY_USER\x10\x05\x12\x11\n\rWRONG_MESSAGE\x10\x06\x12\x0f\n\x0b\x41UTH_FAILED\x10\x07\x12\x16\n\x12\x41UTH_FAILED_BY_CAR\x10\x08\x12\x0b\n\x07TIMEOUT\x10\t\x12\x16\n\x12\x43\x41R_NOT_RESPONDING\x10\x0c\x12\x1b\n\x17\x41UTH_CERT_NOT_YET_VALID\x10\r\x12\x15\n\x11\x41UTH_CERT_EXPIRED\x10\x0e\x12\x0f\n\x0b\x41UDIO_ERROR\x10\x18\x12!\n\x1dPROJECTION_PROCESS_CRASH_LOOP\x10\x1a\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.DisconnectReasonEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISCONNECTREASON']._serialized_start=59
  _globals['_DISCONNECTREASON']._serialized_end=424
  _globals['_DISCONNECTREASON_ENUM']._serialized_start=80
  _globals['_DISCONNECTREASON_ENUM']._serialized_end=424
# @@protoc_insertion_point(module_scope)
