# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/common/PingConfigurationData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/common/PingConfigurationData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/common/PingConfigurationData.proto\x12\x0eoaa.proto.data\"y\n\x11PingConfiguration\x12\x1d\n\x10ping_interval_ns\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x1c\n\x0fping_timeout_ms\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x13\n\x11_ping_interval_nsB\x12\n\x10_ping_timeout_msb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.common.PingConfigurationData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGCONFIGURATION']._serialized_start=58
  _globals['_PINGCONFIGURATION']._serialized_end=179
# @@protoc_insertion_point(module_scope)
