# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/radio/RadioProgramTypeSchemaEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/radio/RadioProgramTypeSchemaEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/radio/RadioProgramTypeSchemaEnum.proto\x12\x0foaa.proto.enums\"X\n\x16RadioProgramTypeSchema\">\n\x04\x45num\x12\x12\n\x0eSCHEMA_UNKNOWN\x10\x00\x12\x12\n\x0eSCHEMA_RDS_PTY\x10\x01\x12\x0e\n\nSCHEMA_ITU\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.radio.RadioProgramTypeSchemaEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADIOPROGRAMTYPESCHEMA']._serialized_start=63
  _globals['_RADIOPROGRAMTYPESCHEMA']._serialized_end=151
  _globals['_RADIOPROGRAMTYPESCHEMA_ENUM']._serialized_start=89
  _globals['_RADIOPROGRAMTYPESCHEMA_ENUM']._serialized_end=151
# @@protoc_insertion_point(module_scope)
