# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelSetupResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelSetupResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.av import AVChannelSetupStatusEnum_pb2 as oaa_dot_av_dot_AVChannelSetupStatusEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/av/AVChannelSetupResponseMessage.proto\x12\x12oaa.proto.messages\x1a%oaa/av/AVChannelSetupStatusEnum.proto\"\x80\x01\n\x16\x41VChannelSetupResponse\x12@\n\x0cmedia_status\x18\x01 \x02(\x0e\x32*.oaa.proto.enums.AVChannelSetupStatus.Enum\x12\x13\n\x0bmax_unacked\x18\x02 \x01(\r\x12\x0f\n\x07\x63onfigs\x18\x03 \x03(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelSetupResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSETUPRESPONSE']._serialized_start=106
  _globals['_AVCHANNELSETUPRESPONSE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
