# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelMediaStatsMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelMediaStatsMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import PingConfigurationData_pb2 as oaa_dot_common_dot_PingConfigurationData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/av/AVChannelMediaStatsMessage.proto\x12\x12oaa.proto.messages\x1a&oaa/common/PingConfigurationData.proto\"N\n\nStatsEntry\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x03\x12\x0f\n\x07minimum\x18\x02 \x01(\x03\x12\x0f\n\x07maximum\x18\x03 \x01(\x03\x12\r\n\x05\x63ount\x18\x04 \x01(\x03\"\x8e\x05\n\x13\x41VChannelMediaStats\x12\x33\n\x08\x64uration\x18\x01 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x14\n\x0ctotal_frames\x18\x02 \x01(\x03\x12\x17\n\x0frendered_frames\x18\x03 \x01(\x03\x12\x16\n\x0e\x64ropped_frames\x18\x04 \x01(\x03\x12:\n\x12video_frame_jitter\x18\x05 \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12:\n\x12video_pacing_delay\x18\x06 \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12\x37\n\x0f\x64\x65\x63ode_duration\x18\x07 \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12\x37\n\x0frender_duration\x18\x08 \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12\x16\n\x0etoo_slow_count\x18\t \x01(\x03\x12\x16\n\x0etoo_fast_count\x18\n \x01(\x03\x12\x39\n\x11overflow_duration\x18\x0b \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12:\n\x12underflow_duration\x18\x0c \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12\x38\n\x10pipeline_latency\x18\r \x01(\x0b\x32\x1e.oaa.proto.messages.StatsEntry\x12\x13\n\x0btotal_bytes\x18\x0e \x01(\x03\x12\x1b\n\x13session_duration_ns\x18\x0f \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelMediaStatsMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSENTRY']._serialized_start=103
  _globals['_STATSENTRY']._serialized_end=181
  _globals['_AVCHANNELMEDIASTATS']._serialized_start=184
  _globals['_AVCHANNELMEDIASTATS']._serialized_end=838
# @@protoc_insertion_point(module_scope)
