# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelSessionTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelSessionTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%oaa/av/AVChannelSessionTypeEnum.proto\x12\x0foaa.proto.enums\"m\n\x14\x41VChannelSessionType\"U\n\x04\x45num\x12\x18\n\x14SESSION_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13SESSION_TYPE_NORMAL\x10\x01\x12\x1a\n\x16SESSION_TYPE_ALTERNATE\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelSessionTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSESSIONTYPE']._serialized_start=58
  _globals['_AVCHANNELSESSIONTYPE']._serialized_end=167
  _globals['_AVCHANNELSESSIONTYPE_ENUM']._serialized_start=82
  _globals['_AVCHANNELSESSIONTYPE_ENUM']._serialized_end=167
# @@protoc_insertion_point(module_scope)
