# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/UiConfigMessages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/UiConfigMessages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1doaa/av/UiConfigMessages.proto\x12\x12oaa.proto.messages\"B\n\x06Insets\x12\x0b\n\x03top\x18\x01 \x01(\r\x12\x0e\n\x06\x62ottom\x18\x02 \x01(\r\x12\x0c\n\x04left\x18\x03 \x01(\r\x12\r\n\x05right\x18\x04 \x01(\r\"\xd5\x01\n\x08UiConfig\x12+\n\x07margins\x18\x01 \x01(\x0b\x32\x1a.oaa.proto.messages.Insets\x12\x32\n\x0e\x63ontent_insets\x18\x02 \x01(\x0b\x32\x1a.oaa.proto.messages.Insets\x12\x39\n\x15stable_content_insets\x18\x03 \x01(\x0b\x32\x1a.oaa.proto.messages.Insets\x12-\n\x08ui_theme\x18\x04 \x01(\x0e\x32\x1b.oaa.proto.messages.UiTheme\"F\n\x13UpdateUiConfigReply\x12/\n\tui_config\x18\x01 \x01(\x0b\x32\x1c.oaa.proto.messages.UiConfig\"J\n\x17UpdateHuUiConfigRequest\x12/\n\tui_config\x18\x01 \x01(\x0b\x32\x1c.oaa.proto.messages.UiConfig*H\n\x07UiTheme\x12\x16\n\x12UI_THEME_AUTOMATIC\x10\x00\x12\x12\n\x0eUI_THEME_LIGHT\x10\x01\x12\x11\n\rUI_THEME_DARK\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.UiConfigMessages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UITHEME']._serialized_start=485
  _globals['_UITHEME']._serialized_end=557
  _globals['_INSETS']._serialized_start=53
  _globals['_INSETS']._serialized_end=119
  _globals['_UICONFIG']._serialized_start=122
  _globals['_UICONFIG']._serialized_end=335
  _globals['_UPDATEUICONFIGREPLY']._serialized_start=337
  _globals['_UPDATEUICONFIGREPLY']._serialized_end=407
  _globals['_UPDATEHUUICONFIGREQUEST']._serialized_start=409
  _globals['_UPDATEHUUICONFIGREQUEST']._serialized_end=483
# @@protoc_insertion_point(module_scope)
