# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/InstrumentClusterMessages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/InstrumentClusterMessages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import NavigationTurnEventMessage_pb2 as oaa_dot_navigation_dot_NavigationTurnEventMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.oaa/navigation/InstrumentClusterMessages.proto\x12\x12oaa.proto.messages\x1a/oaa/navigation/NavigationTurnEventMessage.proto\"\x18\n\x16InstrumentClusterStart\"\x17\n\x15InstrumentClusterStop\"\x9e\x01\n\x19LegacyNavigationTurnEvent\x12\x15\n\rmaneuver_type\x18\x01 \x01(\x05\x12\x13\n\x0bturn_number\x18\x02 \x01(\x05\x12\x15\n\rturn_distance\x18\x03 \x01(\x05\x12>\n\rdistance_unit\x18\x04 \x01(\x0e\x32\'.oaa.proto.messages.DistanceDisplayUnit')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.InstrumentClusterMessages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUMENTCLUSTERSTART']._serialized_start=119
  _globals['_INSTRUMENTCLUSTERSTART']._serialized_end=143
  _globals['_INSTRUMENTCLUSTERSTOP']._serialized_start=145
  _globals['_INSTRUMENTCLUSTERSTOP']._serialized_end=168
  _globals['_LEGACYNAVIGATIONTURNEVENT']._serialized_start=171
  _globals['_LEGACYNAVIGATIONTURNEVENT']._serialized_end=329
# @@protoc_insertion_point(module_scope)
