# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/LaneShapeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/LaneShapeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/navigation/LaneShapeEnum.proto\x12\x0foaa.proto.enums\"\xb9\x01\n\tLaneShape\"\xab\x01\n\x04\x45num\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08STRAIGHT\x10\x01\x12\x0f\n\x0bSLIGHT_LEFT\x10\x02\x12\x10\n\x0cSLIGHT_RIGHT\x10\x03\x12\x0f\n\x0bNORMAL_LEFT\x10\x04\x12\x10\n\x0cNORMAL_RIGHT\x10\x05\x12\x0e\n\nSHARP_LEFT\x10\x06\x12\x0f\n\x0bSHARP_RIGHT\x10\x07\x12\x0f\n\x0bU_TURN_LEFT\x10\x08\x12\x10\n\x0cU_TURN_RIGHT\x10\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.LaneShapeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANESHAPE']._serialized_start=56
  _globals['_LANESHAPE']._serialized_end=241
  _globals['_LANESHAPE_ENUM']._serialized_start=70
  _globals['_LANESHAPE_ENUM']._serialized_end=241
# @@protoc_insertion_point(module_scope)
