# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/navigation/NavigationTypeEnum.proto\x12\x0foaa.proto.enums\"W\n\x0eNavigationType\"E\n\x04\x45num\x12\x16\n\x12NAVIGATION_UNKNOWN\x10\x00\x12\x10\n\x0cTURN_BY_TURN\x10\x01\x12\x13\n\x0fNEXT_TURN_IMAGE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONTYPE']._serialized_start=60
  _globals['_NAVIGATIONTYPE']._serialized_end=147
  _globals['_NAVIGATIONTYPE_ENUM']._serialized_start=78
  _globals['_NAVIGATIONTYPE_ENUM']._serialized_end=147
# @@protoc_insertion_point(module_scope)
