# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationFocusRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationFocusRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2oaa/navigation/NavigationFocusRequestMessage.proto\x12\x12oaa.proto.messages\"O\n\x16NavigationFocusRequest\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.oaa.proto.messages.NavigationFocusType*D\n\x13NavigationFocusType\x12\x14\n\x10NAV_FOCUS_NATIVE\x10\x01\x12\x17\n\x13NAV_FOCUS_PROJECTED\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationFocusRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONFOCUSTYPE']._serialized_start=155
  _globals['_NAVIGATIONFOCUSTYPE']._serialized_end=223
  _globals['_NAVIGATIONFOCUSREQUEST']._serialized_start=74
  _globals['_NAVIGATIONFOCUSREQUEST']._serialized_end=153
# @@protoc_insertion_point(module_scope)
