# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/VehicleEnergyForecastMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/VehicleEnergyForecastMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1oaa/navigation/VehicleEnergyForecastMessage.proto\x12\x12oaa.proto.messages\"?\n\x1cVehicleEnergyForecastMessage\x12\x1f\n\x17vehicle_energy_forecast\x18\x01 \x01(\x0c\"\xa3\x03\n\x15VehicleEnergyForecast\x12\x41\n\x13\x65nergy_at_next_stop\x18\x01 \x01(\x0b\x32$.oaa.proto.messages.EnergyAtDistance\x12?\n\x11\x64istance_to_empty\x18\x02 \x01(\x0b\x32$.oaa.proto.messages.EnergyAtDistance\x12=\n\x10\x66orecast_quality\x18\x03 \x01(\x0e\x32#.oaa.proto.messages.ForecastQuality\x12L\n\x12next_charging_stop\x18\x04 \x01(\x0b\x32\x30.oaa.proto.messages.EnergyChargingStationDetails\x12\x35\n\x0cstop_details\x18\x05 \x03(\x0b\x32\x1f.oaa.proto.messages.StopDetails\x12\x42\n\x13\x64\x61ta_authorizations\x18\x06 \x03(\x0b\x32%.oaa.proto.messages.DataAuthorization\"o\n\x10\x45nergyAtDistance\x12\x17\n\x0f\x64istance_meters\x18\x01 \x01(\x05\x12!\n\x19\x61rrival_battery_energy_wh\x18\x02 \x01(\x05\x12\x1f\n\x17time_to_arrival_seconds\x18\x04 \x01(\x05\"\x87\x01\n\x1c\x45nergyChargingStationDetails\x12\x1f\n\x17min_departure_energy_wh\x18\x01 \x01(\x05\x12\x1d\n\x15max_rated_power_watts\x18\x02 \x01(\x05\x12\'\n\x1f\x65stimated_charging_time_seconds\x18\x03 \x01(\x05\"\x9d\x01\n\x0bStopDetails\x12\x45\n\x17\x65xpected_arrival_energy\x18\x01 \x01(\x0b\x32$.oaa.proto.messages.EnergyAtDistance\x12G\n\rcharging_info\x18\x02 \x01(\x0b\x32\x30.oaa.proto.messages.EnergyChargingStationDetails\"\x1f\n\x11\x44\x61taAuthorization\x12\n\n\x02id\x18\x01 \x01(\t*d\n\x0f\x46orecastQuality\x12\x1c\n\x18\x46ORECAST_QUALITY_UNKNOWN\x10\x00\x12\x18\n\x14\x46ORECAST_QUALITY_LOW\x10\x01\x12\x19\n\x15\x46ORECAST_QUALITY_HIGH\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.VehicleEnergyForecastMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTQUALITY']._serialized_start=1004
  _globals['_FORECASTQUALITY']._serialized_end=1104
  _globals['_VEHICLEENERGYFORECASTMESSAGE']._serialized_start=73
  _globals['_VEHICLEENERGYFORECASTMESSAGE']._serialized_end=136
  _globals['_VEHICLEENERGYFORECAST']._serialized_start=139
  _globals['_VEHICLEENERGYFORECAST']._serialized_end=558
  _globals['_ENERGYATDISTANCE']._serialized_start=560
  _globals['_ENERGYATDISTANCE']._serialized_end=671
  _globals['_ENERGYCHARGINGSTATIONDETAILS']._serialized_start=674
  _globals['_ENERGYCHARGINGSTATIONDETAILS']._serialized_end=809
  _globals['_STOPDETAILS']._serialized_start=812
  _globals['_STOPDETAILS']._serialized_end=969
  _globals['_DATAAUTHORIZATION']._serialized_start=971
  _globals['_DATAAUTHORIZATION']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
