# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationFocusResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationFocusResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import NavigationFocusRequestMessage_pb2 as oaa_dot_navigation_dot_NavigationFocusRequestMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3oaa/navigation/NavigationFocusResponseMessage.proto\x12\x12oaa.proto.messages\x1a\x32oaa/navigation/NavigationFocusRequestMessage.proto\"P\n\x17NavigationFocusResponse\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.oaa.proto.messages.NavigationFocusType')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationFocusResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONFOCUSRESPONSE']._serialized_start=127
  _globals['_NAVIGATIONFOCUSRESPONSE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
