# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/navigation/NavigationDistanceMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/navigation/NavigationDistanceMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.navigation import NavigationDistanceDisplayData_pb2 as oaa_dot_navigation_dot_NavigationDistanceDisplayData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.oaa/navigation/NavigationDistanceMessage.proto\x12\x12oaa.proto.messages\x1a\x32oaa/navigation/NavigationDistanceDisplayData.proto\"\xb0\x01\n\x12NavigationDistance\x12\x39\n\x08\x64istance\x18\x01 \x02(\x0b\x32\'.oaa.proto.data.NavigationDistanceValue\x12\x10\n\x08\x65ta_text\x18\x02 \x02(\t\x12\x13\n\x0b\x65ta_seconds\x18\x03 \x02(\x05\x12\x38\n\x04info\x18\x08 \x01(\x0b\x32*.oaa.proto.messages.NavigationDistanceInfo\"\xf9\x01\n\x16NavigationDistanceInfo\x12:\n\x07\x64isplay\x18\x01 \x01(\x0b\x32).oaa.proto.data.NavigationDistanceDisplay\x12\x44\n\x11\x61lternate_display\x18\x02 \x03(\x0b\x32).oaa.proto.data.NavigationDistanceDisplay\x12\x44\n\roneof_display\x18\x04 \x01(\x0b\x32+.oaa.proto.messages.NavigationDistanceOneofH\x00\x42\x17\n\x15oneof_display_wrapper\"W\n\x17NavigationDistanceOneof\x12<\n\x07\x65ntries\x18\x01 \x03(\x0b\x32+.oaa.proto.messages.NavigationDistanceEntry\"z\n\x17NavigationDistanceEntry\x12:\n\x07\x64isplay\x18\x01 \x01(\x0b\x32).oaa.proto.data.NavigationDistanceDisplay\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x14\n\x08metadata\x18\x03 \x03(\x05\x42\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.navigation.NavigationDistanceMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONDISTANCEENTRY'].fields_by_name['metadata']._loaded_options = None
  _globals['_NAVIGATIONDISTANCEENTRY'].fields_by_name['metadata']._serialized_options = b'\020\001'
  _globals['_NAVIGATIONDISTANCE']._serialized_start=123
  _globals['_NAVIGATIONDISTANCE']._serialized_end=299
  _globals['_NAVIGATIONDISTANCEINFO']._serialized_start=302
  _globals['_NAVIGATIONDISTANCEINFO']._serialized_end=551
  _globals['_NAVIGATIONDISTANCEONEOF']._serialized_start=553
  _globals['_NAVIGATIONDISTANCEONEOF']._serialized_end=640
  _globals['_NAVIGATIONDISTANCEENTRY']._serialized_start=642
  _globals['_NAVIGATIONDISTANCEENTRY']._serialized_end=764
# @@protoc_insertion_point(module_scope)
