# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/audio/AudioFocusTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/audio/AudioFocusTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/audio/AudioFocusTypeEnum.proto\x12\x0foaa.proto.enums\"j\n\x0e\x41udioFocusType\"X\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04GAIN\x10\x01\x12\x12\n\x0eGAIN_TRANSIENT\x10\x02\x12\x1b\n\x17GAIN_TRANSIENT_MAY_DUCK\x10\x03\x12\x0b\n\x07RELEASE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.audio.AudioFocusTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFOCUSTYPE']._serialized_start=55
  _globals['_AUDIOFOCUSTYPE']._serialized_end=161
  _globals['_AUDIOFOCUSTYPE_ENUM']._serialized_start=73
  _globals['_AUDIOFOCUSTYPE_ENUM']._serialized_end=161
# @@protoc_insertion_point(module_scope)
