# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/audio/AudioFocusResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/audio/AudioFocusResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.audio import AudioFocusStateEnum_pb2 as oaa_dot_audio_dot_AudioFocusStateEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)oaa/audio/AudioFocusResponseMessage.proto\x12\x12oaa.proto.messages\x1a#oaa/audio/AudioFocusStateEnum.proto\"g\n\x12\x41udioFocusResponse\x12@\n\x11\x61udio_focus_state\x18\x01 \x02(\x0e\x32%.oaa.proto.enums.AudioFocusState.Enum\x12\x0f\n\x07granted\x18\x02 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.audio.AudioFocusResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFOCUSRESPONSE']._serialized_start=102
  _globals['_AUDIOFOCUSRESPONSE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
