# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelSetupStatusEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelSetupStatusEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%oaa/av/AVChannelSetupStatusEnum.proto\x12\x0foaa.proto.enums\":\n\x14\x41VChannelSetupStatus\"\"\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x12\x06\n\x02OK\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelSetupStatusEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSETUPSTATUS']._serialized_start=58
  _globals['_AVCHANNELSETUPSTATUS']._serialized_end=116
  _globals['_AVCHANNELSETUPSTATUS_ENUM']._serialized_start=82
  _globals['_AVCHANNELSETUPSTATUS_ENUM']._serialized_end=116
# @@protoc_insertion_point(module_scope)
