# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelStartIndicationMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelStartIndicationMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.av import AVChannelMediaConfigMessage_pb2 as oaa_dot_av_dot_AVChannelMediaConfigMessage__pb2
from oaa.av import AVChannelSessionTypeEnum_pb2 as oaa_dot_av_dot_AVChannelSessionTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,oaa/av/AVChannelStartIndicationMessage.proto\x12\x12oaa.proto.messages\x1a(oaa/av/AVChannelMediaConfigMessage.proto\x1a%oaa/av/AVChannelSessionTypeEnum.proto\"\xbd\x01\n\x18\x41VChannelStartIndication\x12\x0f\n\x07session\x18\x01 \x02(\x05\x12\x0e\n\x06\x63onfig\x18\x02 \x02(\r\x12@\n\x0csession_type\x18\x03 \x01(\x0e\x32*.oaa.proto.enums.AVChannelSessionType.Enum\x12>\n\x0cmedia_config\x18\x04 \x01(\x0b\x32(.oaa.proto.messages.AVChannelMediaConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelStartIndicationMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSTARTINDICATION']._serialized_start=150
  _globals['_AVCHANNELSTARTINDICATION']._serialized_end=339
# @@protoc_insertion_point(module_scope)
