# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.av import AVStreamTypeEnum_pb2 as oaa_dot_av_dot_AVStreamTypeEnum__pb2
from oaa.av import AndroidKeycodeEnum_pb2 as oaa_dot_av_dot_AndroidKeycodeEnum__pb2
from oaa.audio import AudioTypeEnum_pb2 as oaa_dot_audio_dot_AudioTypeEnum__pb2
from oaa.audio import AudioConfigData_pb2 as oaa_dot_audio_dot_AudioConfigData__pb2
from oaa.video import VideoConfigData_pb2 as oaa_dot_video_dot_VideoConfigData__pb2
from oaa.video import DisplayTypeEnum_pb2 as oaa_dot_video_dot_DisplayTypeEnum__pb2
from oaa.video import ColorSchemeSupportEnum_pb2 as oaa_dot_video_dot_ColorSchemeSupportEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aoaa/av/AVChannelData.proto\x12\x0eoaa.proto.data\x1a\x1doaa/av/AVStreamTypeEnum.proto\x1a\x1foaa/av/AndroidKeycodeEnum.proto\x1a\x1doaa/audio/AudioTypeEnum.proto\x1a\x1foaa/audio/AudioConfigData.proto\x1a\x1foaa/video/VideoConfigData.proto\x1a\x1foaa/video/DisplayTypeEnum.proto\x1a&oaa/video/ColorSchemeSupportEnum.proto\"\xad\x03\n\tAVChannel\x12\x37\n\x0bstream_type\x18\x01 \x01(\x0e\x32\".oaa.proto.enums.AVStreamType.Enum\x12\x33\n\naudio_type\x18\x02 \x01(\x0e\x32\x1f.oaa.proto.enums.AudioType.Enum\x12\x32\n\raudio_configs\x18\x03 \x03(\x0b\x32\x1b.oaa.proto.data.AudioConfig\x12\x32\n\rvideo_configs\x18\x04 \x03(\x0b\x32\x1b.oaa.proto.data.VideoConfig\x12\x12\n\nchannel_id\x18\x06 \x01(\r\x12\x37\n\x0c\x64isplay_type\x18\x07 \x01(\x0e\x32!.oaa.proto.enums.DisplayType.Enum\x12\x35\n\x07keycode\x18\x08 \x01(\x0e\x32$.oaa.proto.enums.AndroidKeycode.Enum\x12\x46\n\x14\x63olor_scheme_support\x18\t \x01(\x0e\x32(.oaa.proto.enums.ColorSchemeSupport.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNEL']._serialized_start=281
  _globals['_AVCHANNEL']._serialized_end=710
# @@protoc_insertion_point(module_scope)
