# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/UiConfigRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/UiConfigRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/video/UiConfigRequestMessage.proto\x12\x12oaa.proto.messages\"\x1e\n\rUiConfigValue\x12\r\n\x05value\x18\x01 \x01(\r\"`\n\rUiConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x0c\x63onfig_value\x18\x02 \x01(\x0b\x32!.oaa.proto.messages.UiConfigValueH\x00\x42\x07\n\x05value\"\x88\x01\n\x0cUiConfigData\x12:\n\x0fprimary_configs\x18\x01 \x03(\x0b\x32!.oaa.proto.messages.UiConfigEntry\x12<\n\x11secondary_configs\x18\x02 \x03(\x0b\x32!.oaa.proto.messages.UiConfigEntry\"C\n\x0fUiConfigRequest\x12\x30\n\x06\x63onfig\x18\x01 \x01(\x0b\x32 .oaa.proto.messages.UiConfigData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.UiConfigRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UICONFIGVALUE']._serialized_start=62
  _globals['_UICONFIGVALUE']._serialized_end=92
  _globals['_UICONFIGENTRY']._serialized_start=94
  _globals['_UICONFIGENTRY']._serialized_end=190
  _globals['_UICONFIGDATA']._serialized_start=193
  _globals['_UICONFIGDATA']._serialized_end=329
  _globals['_UICONFIGREQUEST']._serialized_start=331
  _globals['_UICONFIGREQUEST']._serialized_end=398
# @@protoc_insertion_point(module_scope)
