# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/video/VideoConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/video/VideoConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.video import VideoResolutionEnum_pb2 as oaa_dot_video_dot_VideoResolutionEnum__pb2
from oaa.video import VideoFPSEnum_pb2 as oaa_dot_video_dot_VideoFPSEnum__pb2
from oaa.av import MediaCodecTypeEnum_pb2 as oaa_dot_av_dot_MediaCodecTypeEnum__pb2
from oaa.video import AdditionalVideoConfigData_pb2 as oaa_dot_video_dot_AdditionalVideoConfigData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1foaa/video/VideoConfigData.proto\x12\x0eoaa.proto.data\x1a#oaa/video/VideoResolutionEnum.proto\x1a\x1coaa/video/VideoFPSEnum.proto\x1a\x1foaa/av/MediaCodecTypeEnum.proto\x1a)oaa/video/AdditionalVideoConfigData.proto\"\xa3\x03\n\x0bVideoConfig\x12?\n\x10video_resolution\x18\x01 \x01(\x0e\x32%.oaa.proto.enums.VideoResolution.Enum\x12\x31\n\tvideo_fps\x18\x02 \x01(\x0e\x32\x1e.oaa.proto.enums.VideoFPS.Enum\x12\x14\n\x0cmargin_width\x18\x03 \x01(\r\x12\x15\n\rmargin_height\x18\x04 \x01(\r\x12\x0b\n\x03\x64pi\x18\x05 \x01(\r\x12 \n\x18\x64\x65\x63oder_additional_depth\x18\x06 \x01(\r\x12\x18\n\x10viewing_distance\x18\x07 \x01(\r\x12\x1d\n\x15pixel_aspect_ratio_e4\x18\x08 \x01(\r\x12\x14\n\x0creal_density\x18\t \x01(\r\x12\x33\n\x05\x63odec\x18\n \x01(\x0e\x32$.oaa.proto.enums.MediaCodecType.Enum\x12@\n\x11\x61\x64\x64itional_config\x18\x0b \x01(\x0b\x32%.oaa.proto.data.AdditionalVideoConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.video.VideoConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOCONFIG']._serialized_start=195
  _globals['_VIDEOCONFIG']._serialized_end=614
# @@protoc_insertion_point(module_scope)
