# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/GPSLocationData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/GPSLocationData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n oaa/sensor/GPSLocationData.proto\x12\x0eoaa.proto.data\"v\n\x0bGPSLocation\x12\x10\n\x08latitude\x18\x02 \x02(\x05\x12\x11\n\tlongitude\x18\x03 \x02(\x05\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\r\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x05\x12\r\n\x05speed\x18\x06 \x01(\x05\x12\x0f\n\x07\x62\x65\x61ring\x18\x07 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.GPSLocationData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPSLOCATION']._serialized_start=52
  _globals['_GPSLOCATION']._serialized_end=170
# @@protoc_insertion_point(module_scope)
