# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/LightData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/LightData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.sensor import HeadlightStatusEnum_pb2 as oaa_dot_sensor_dot_HeadlightStatusEnum__pb2
from oaa.sensor import IndicatorStatusEnum_pb2 as oaa_dot_sensor_dot_IndicatorStatusEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aoaa/sensor/LightData.proto\x12\x0eoaa.proto.data\x1a$oaa/sensor/HeadlightStatusEnum.proto\x1a$oaa/sensor/IndicatorStatusEnum.proto\"\x94\x01\n\x05Light\x12\x38\n\theadlight\x18\x01 \x01(\x0e\x32%.oaa.proto.enums.HeadlightStatus.Enum\x12\x38\n\tindicator\x18\x02 \x01(\x0e\x32%.oaa.proto.enums.IndicatorStatus.Enum\x12\x17\n\x0fhazard_light_on\x18\x03 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.LightData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIGHT']._serialized_start=123
  _globals['_LIGHT']._serialized_end=271
# @@protoc_insertion_point(module_scope)
