# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/SensorErrorStatusEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/SensorErrorStatusEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&oaa/sensor/SensorErrorStatusEnum.proto\x12\x0foaa.proto.enums\"b\n\x11SensorErrorStatus\"M\n\x04\x45num\x12\r\n\tSENSOR_OK\x10\x01\x12\x1a\n\x16SENSOR_ERROR_TRANSIENT\x10\x02\x12\x1a\n\x16SENSOR_ERROR_PERMANENT\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.SensorErrorStatusEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORERRORSTATUS']._serialized_start=59
  _globals['_SENSORERRORSTATUS']._serialized_end=157
  _globals['_SENSORERRORSTATUS_ENUM']._serialized_start=80
  _globals['_SENSORERRORSTATUS_ENUM']._serialized_end=157
# @@protoc_insertion_point(module_scope)
