# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/SensorChannelMessageIdsEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/SensorChannelMessageIdsEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,oaa/sensor/SensorChannelMessageIdsEnum.proto\x12\roaa.proto.ids\"\x8e\x01\n\x14SensorChannelMessage\"v\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x14\n\x0eSENSOR_REQUEST\x10\x81\x80\x02\x12\x1b\n\x15SENSOR_START_RESPONSE\x10\x82\x80\x02\x12\x1d\n\x17SENSOR_EVENT_INDICATION\x10\x83\x80\x02\x12\x12\n\x0cSENSOR_ERROR\x10\x84\x80\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.SensorChannelMessageIdsEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORCHANNELMESSAGE']._serialized_start=64
  _globals['_SENSORCHANNELMESSAGE']._serialized_end=206
  _globals['_SENSORCHANNELMESSAGE_ENUM']._serialized_start=88
  _globals['_SENSORCHANNELMESSAGE_ENUM']._serialized_end=206
# @@protoc_insertion_point(module_scope)
