"""
NemoHeadUnit-Wireless — config_schema

Lightweight schema descriptor for module configuration keys.

Usage (inside a module):

    from shared.config_schema import field_string, field_int, field_float, field_enum, field_bool

    _SCHEMA = {
        "pin":     field_string(default="1234"),
        "volume":  field_int(default=80, min=0, max=100),
        "gain":    field_float(default=1.0, min=0.0, max=2.0),
        "mode":    field_enum(default="auto", choices=["off", "auto", "on"]),
        "enabled": field_bool(default=True),
    }

Pass _SCHEMA to cfg.get():

    cfg.get(defaults=_DEFAULTS, schema=_SCHEMA)

config_manager stores the schema in RAM and echoes it in every
config.response so config_ui can render the correct widget.

Validation
----------
validate_value(field, value) → raises ValueError on mismatch.
config_manager calls this in on_config_set before persisting.

Structured field types (proto-derived)
---------------------------------------
Three additional types support proto-derived schemas generated by
proto_utils.schema_from_proto_message():

    ConfigFieldMessage  — a nested proto message.
                          optional=True → rendered as a collapsible
                          section with an enable/disable checkbox.
                          fields is a dict[str, AnyFieldType].

    ConfigFieldList     — a proto repeated field.
                          item_schema describes one element of the list.
                          The config value is a list of dicts (one per
                          element), each matching item_schema.

    ConfigFieldOneof    — a proto oneof group.
                          branches maps each branch name to its schema.
                          Rendered as a radio-button selector; only the
                          active branch is populated/serialised.
                          active_branch holds the currently selected name.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

# Accepted truthy/falsy strings for bool coercion (case-insensitive)
_BOOL_TRUE  = {"true", "1", "yes", "on"}
_BOOL_FALSE = {"false", "0", "no", "off"}

# Type alias for any schema node (scalar or structured)
AnyFieldSchema = Any  # ConfigFieldSchema | ConfigFieldMessage | ConfigFieldList | ConfigFieldOneof


# ---------------------------------------------------------------------------
# Scalar schema descriptor (original)
# ---------------------------------------------------------------------------

@dataclass
class ConfigFieldSchema:
    type:    Literal["int", "float", "string", "enum", "bool"]
    default: object

    # int / float only
    min: int | float | None = None
    max: int | float | None = None

    # enum only
    choices: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialise to a plain dict suitable for bus payloads."""
        d: dict = {"type": self.type, "default": self.default}
        if self.min is not None:
            d["min"] = self.min
        if self.max is not None:
            d["max"] = self.max
        if self.choices:
            d["choices"] = list(self.choices)
        return d

    @staticmethod
    def from_dict(d: dict) -> "ConfigFieldSchema":
        """Deserialise from a plain dict (received via bus payload)."""
        return ConfigFieldSchema(
            type=d["type"],
            default=d.get("default"),
            min=d.get("min"),
            max=d.get("max"),
            choices=d.get("choices", []),
        )


# ---------------------------------------------------------------------------
# Structured schema descriptors (proto-derived)
# ---------------------------------------------------------------------------

@dataclass
class ConfigFieldMessage:
    """A nested proto message.

    fields:   dict mapping field names to their schema (any AnyFieldSchema).
    optional: if True, the entire message is opt-in (checkbox in the UI).
              When disabled, the message is omitted from the serialised proto.
    """
    fields:   dict[str, AnyFieldSchema]
    optional: bool = False

    def to_dict(self) -> dict:
        return {
            "type":     "message",
            "optional": self.optional,
            "fields":   {k: _node_to_dict(v) for k, v in self.fields.items()},
        }

    @staticmethod
    def from_dict(d: dict) -> "ConfigFieldMessage":
        return ConfigFieldMessage(
            fields={k: _node_from_dict(v) for k, v in d.get("fields", {}).items()},
            optional=d.get("optional", False),
        )


@dataclass
class ConfigFieldList:
    """A proto repeated field.

    item_schema: schema describing a single list element.
                 May be a ConfigFieldMessage (most common) or a scalar
                 ConfigFieldSchema for repeated scalars.
    default:     list of default item values (dicts for messages, scalars
                 for scalar items). Defaults to a single default element.
    """
    item_schema: AnyFieldSchema
    default:     list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "type":        "list",
            "item_schema": _node_to_dict(self.item_schema),
            "default":     self.default,
        }

    @staticmethod
    def from_dict(d: dict) -> "ConfigFieldList":
        return ConfigFieldList(
            item_schema=_node_from_dict(d["item_schema"]),
            default=d.get("default", []),
        )


@dataclass
class ConfigFieldOneof:
    """A proto oneof group.

    branches:      dict mapping each branch name to its schema
                   (typically ConfigFieldMessage).
    active_branch: name of the currently selected branch (radio button).
                   Must be a key in branches.
    """
    branches:      dict[str, AnyFieldSchema]
    active_branch: str

    def __post_init__(self) -> None:
        if self.active_branch not in self.branches:
            raise ValueError(
                f"ConfigFieldOneof: active_branch {self.active_branch!r} "
                f"is not in branches {list(self.branches)}"
            )

    def to_dict(self) -> dict:
        return {
            "type":          "oneof",
            "active_branch": self.active_branch,
            "branches":      {k: _node_to_dict(v) for k, v in self.branches.items()},
        }

    @staticmethod
    def from_dict(d: dict) -> "ConfigFieldOneof":
        return ConfigFieldOneof(
            branches={k: _node_from_dict(v) for k, v in d.get("branches", {}).items()},
            active_branch=d["active_branch"],
        )


# ---------------------------------------------------------------------------
# Recursive serialisation helpers (private)
# ---------------------------------------------------------------------------

def _node_to_dict(node: AnyFieldSchema) -> dict:
    """Serialise any schema node to a plain dict."""
    if isinstance(node, (ConfigFieldMessage, ConfigFieldList, ConfigFieldOneof, ConfigFieldSchema)):
        return node.to_dict()
    raise TypeError(f"_node_to_dict: unsupported schema node type {type(node)!r}")


def _node_from_dict(d: dict) -> AnyFieldSchema:
    """Deserialise any schema node from a plain dict."""
    t = d.get("type")
    if t == "message":
        return ConfigFieldMessage.from_dict(d)
    if t == "list":
        return ConfigFieldList.from_dict(d)
    if t == "oneof":
        return ConfigFieldOneof.from_dict(d)
    # Scalar types: int, float, string, enum, bool
    return ConfigFieldSchema.from_dict(d)


# ---------------------------------------------------------------------------
# Convenience constructors (scalars — unchanged)
# ---------------------------------------------------------------------------

def field_string(default: str = "") -> ConfigFieldSchema:
    return ConfigFieldSchema(type="string", default=default)


def field_int(
    default: int = 0,
    min: int | None = None,
    max: int | None = None,
) -> ConfigFieldSchema:
    return ConfigFieldSchema(type="int", default=default, min=min, max=max)


def field_float(
    default: float = 0.0,
    min: float | None = None,
    max: float | None = None,
) -> ConfigFieldSchema:
    return ConfigFieldSchema(type="float", default=default, min=min, max=max)


def field_enum(default: str, choices: list[str]) -> ConfigFieldSchema:
    if default not in choices:
        raise ValueError(
            f"field_enum: default {default!r} is not in choices {choices}"
        )
    return ConfigFieldSchema(type="enum", default=default, choices=choices)


def field_bool(default: bool = False) -> ConfigFieldSchema:
    return ConfigFieldSchema(type="bool", default=bool(default))


# ---------------------------------------------------------------------------
# Schema serialisation helpers (updated to support structured nodes)
# ---------------------------------------------------------------------------

def schema_to_dict(schema: dict[str, AnyFieldSchema]) -> dict:
    """Convert a full module schema to a bus-safe plain dict."""
    return {k: _node_to_dict(v) for k, v in schema.items()}


def schema_from_dict(d: dict) -> dict[str, AnyFieldSchema]:
    """Restore a full module schema from a bus payload dict."""
    return {k: _node_from_dict(v) for k, v in d.items()}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_value(schema_field: ConfigFieldSchema, value: object) -> object:
    """
    Validate *value* against *schema_field*.

    Returns the (possibly coerced) value on success.
    Raises ValueError with a human-readable message on failure.

    Coercion rules
    --------------
    - bool:       bool passthrough; str coerced via _BOOL_TRUE/_BOOL_FALSE
    - int/float:  str → int/float (tolerates values coming as strings from QLineEdit)
    - string:     value is str-cast
    - enum:       value must be one of choices (str comparison)

    Note: ConfigFieldMessage / ConfigFieldList / ConfigFieldOneof validation
    is handled recursively by config_manager, not here.
    """
    t = schema_field.type

    if t == "bool":
        if isinstance(value, bool):
            return value
        if isinstance(value, int):
            return bool(value)
        str_val = str(value).strip().lower()
        if str_val in _BOOL_TRUE:
            return True
        if str_val in _BOOL_FALSE:
            return False
        raise ValueError(
            f"expected bool (true/false/yes/no/on/off/1/0), got {value!r}"
        )

    if t == "string":
        return str(value)

    if t == "enum":
        str_value = str(value)
        if str_value not in schema_field.choices:
            raise ValueError(
                f"expected one of {schema_field.choices}, got {value!r}"
            )
        return str_value

    if t == "int":
        try:
            coerced = int(value)  # type: ignore[arg-type]
        except (TypeError, ValueError):
            raise ValueError(f"expected int, got {type(value).__name__} ({value!r})")
        if schema_field.min is not None and coerced < schema_field.min:
            raise ValueError(f"{coerced} is below minimum {schema_field.min}")
        if schema_field.max is not None and coerced > schema_field.max:
            raise ValueError(f"{coerced} is above maximum {schema_field.max}")
        return coerced

    if t == "float":
        try:
            coerced = float(value)  # type: ignore[arg-type]
        except (TypeError, ValueError):
            raise ValueError(f"expected float, got {type(value).__name__} ({value!r})")
        if schema_field.min is not None and coerced < schema_field.min:
            raise ValueError(f"{coerced} is below minimum {schema_field.min}")
        if schema_field.max is not None and coerced > schema_field.max:
            raise ValueError(f"{coerced} is above maximum {schema_field.max}")
        return coerced

    raise ValueError(f"unknown schema type {t!r}")
