# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ControlChannelConfigData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ControlChannelConfigData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/control/ControlChannelConfigData.proto\x12\x0eoaa.proto.data\"Z\n\x14\x43ontrolChannelParams\x12\x0f\n\x07param_1\x18\x01 \x01(\r\x12\x0f\n\x07param_2\x18\x02 \x01(\r\x12\x0f\n\x07param_3\x18\x03 \x01(\r\x12\x0f\n\x07param_4\x18\x04 \x01(\r\"L\n\x14\x43ontrolChannelConfig\x12\x34\n\x06params\x18\x01 \x01(\x0b\x32$.oaa.proto.data.ControlChannelParams')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ControlChannelConfigData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLCHANNELPARAMS']._serialized_start=62
  _globals['_CONTROLCHANNELPARAMS']._serialized_end=152
  _globals['_CONTROLCHANNELCONFIG']._serialized_start=154
  _globals['_CONTROLCHANNELCONFIG']._serialized_end=230
# @@protoc_insertion_point(module_scope)
