# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ControlMessageIdsEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ControlMessageIdsEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/control/ControlMessageIdsEnum.proto\x12\roaa.proto.ids\"\xbc\x05\n\x0e\x43ontrolMessage\"\xa9\x05\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0fVERSION_REQUEST\x10\x01\x12\x14\n\x10VERSION_RESPONSE\x10\x02\x12\x11\n\rSSL_HANDSHAKE\x10\x03\x12\x11\n\rAUTH_COMPLETE\x10\x04\x12\x1d\n\x19SERVICE_DISCOVERY_REQUEST\x10\x05\x12\x1e\n\x1aSERVICE_DISCOVERY_RESPONSE\x10\x06\x12\x18\n\x14\x43HANNEL_OPEN_REQUEST\x10\x07\x12\x19\n\x15\x43HANNEL_OPEN_RESPONSE\x10\x08\x12\x10\n\x0cPING_REQUEST\x10\x0b\x12\x11\n\rPING_RESPONSE\x10\x0c\x12\x1c\n\x18NAVIGATION_FOCUS_REQUEST\x10\r\x12\x1d\n\x19NAVIGATION_FOCUS_RESPONSE\x10\x0e\x12\x14\n\x10SHUTDOWN_REQUEST\x10\x0f\x12\x15\n\x11SHUTDOWN_RESPONSE\x10\x10\x12\x19\n\x15VOICE_SESSION_REQUEST\x10\x11\x12\x17\n\x13\x41UDIO_FOCUS_REQUEST\x10\x12\x12\x18\n\x14\x41UDIO_FOCUS_RESPONSE\x10\x13\x12!\n\x1d\x43\x41R_CONNECTED_DEVICES_REQUEST\x10\x14\x12\"\n\x1e\x43\x41R_CONNECTED_DEVICES_RESPONSE\x10\x15\x12\x17\n\x13USER_SWITCH_REQUEST\x10\x16\x12\x1f\n\x1b\x42\x41TTERY_STATUS_NOTIFICATION\x10\x17\x12\x1c\n\x18\x43\x41LL_AVAILABILITY_STATUS\x10\x18\x12\x18\n\x14USER_SWITCH_RESPONSE\x10\x19\x12\x1c\n\x18SERVICE_DISCOVERY_UPDATE\x10\x1a\x12\x1e\n\x1a\x43HANNEL_CLOSE_NOTIFICATION\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ControlMessageIdsEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLMESSAGE']._serialized_start=59
  _globals['_CONTROLMESSAGE']._serialized_end=759
  _globals['_CONTROLMESSAGE_ENUM']._serialized_start=78
  _globals['_CONTROLMESSAGE_ENUM']._serialized_end=759
# @@protoc_insertion_point(module_scope)
