# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ServiceDiscoveryRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ServiceDiscoveryRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import SessionInfoData_pb2 as oaa_dot_common_dot_SessionInfoData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0oaa/control/ServiceDiscoveryRequestMessage.proto\x12\x12oaa.proto.messages\x1a oaa/common/SessionInfoData.proto\"\xc6\x01\n\x17ServiceDiscoveryRequest\x12\x18\n\x10phone_icon_small\x18\x01 \x01(\x0c\x12\x19\n\x11phone_icon_medium\x18\x02 \x01(\x0c\x12\x18\n\x10phone_icon_large\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65vice_name\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x65vice_brand\x18\x05 \x01(\t\x12\x31\n\x0csession_info\x18\x06 \x01(\x0b\x32\x1b.oaa.proto.data.SessionInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ServiceDiscoveryRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEDISCOVERYREQUEST']._serialized_start=107
  _globals['_SERVICEDISCOVERYREQUEST']._serialized_end=305
# @@protoc_insertion_point(module_scope)
