# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ControlChannelConfigMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ControlChannelConfigMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import ControlChannelConfigData_pb2 as oaa_dot_control_dot_ControlChannelConfigData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-oaa/control/ControlChannelConfigMessage.proto\x12\x12oaa.proto.messages\x1a*oaa/control/ControlChannelConfigData.proto\"S\n\x1b\x43ontrolChannelConfigWrapper\x12\x34\n\x06\x63onfig\x18\x01 \x01(\x0b\x32$.oaa.proto.data.ControlChannelConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ControlChannelConfigMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLCHANNELCONFIGWRAPPER']._serialized_start=113
  _globals['_CONTROLCHANNELCONFIGWRAPPER']._serialized_end=196
# @@protoc_insertion_point(module_scope)
