# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/PhoneCapabilitiesMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/PhoneCapabilitiesMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import CapabilityData_pb2 as oaa_dot_control_dot_CapabilityData__pb2
from oaa.control import PhoneCapabilitiesData_pb2 as oaa_dot_control_dot_PhoneCapabilitiesData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*oaa/control/PhoneCapabilitiesMessage.proto\x12\x0eoaa.proto.data\x1a oaa/control/CapabilityData.proto\x1a\'oaa/control/PhoneCapabilitiesData.proto\"\xf5\x02\n\x11PhoneCapabilities\x12\x35\n\rfeature_flags\x18\x01 \x01(\x0b\x32\x1e.oaa.proto.data.CapabilityFlag\x12/\n\x0b\x64\x65vice_info\x18\x02 \x01(\x0b\x32\x1a.oaa.proto.data.DeviceInfo\x12@\n\x11\x63onnection_config\x18\x03 \x01(\x0b\x32%.oaa.proto.data.PhoneConnectionConfig\x12<\n\x14\x64isplay_capabilities\x18\x04 \x01(\x0b\x32\x1e.oaa.proto.data.CapabilityPair\x12\x35\n\x0c\x63\x61pabilities\x18\x05 \x03(\x0b\x32\x1f.oaa.proto.data.CapabilityEntry\x12\x41\n\x10phone_identifier\x18\x07 \x03(\x0e\x32#.oaa.proto.data.PhoneIdentifierTypeB\x02\x10\x01*3\n\x13PhoneIdentifierType\x12\x1c\n\x18PHONE_IDENTIFIER_UNKNOWN\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.PhoneCapabilitiesMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHONECAPABILITIES'].fields_by_name['phone_identifier']._loaded_options = None
  _globals['_PHONECAPABILITIES'].fields_by_name['phone_identifier']._serialized_options = b'\020\001'
  _globals['_PHONEIDENTIFIERTYPE']._serialized_start=513
  _globals['_PHONEIDENTIFIERTYPE']._serialized_end=564
  _globals['_PHONECAPABILITIES']._serialized_start=138
  _globals['_PHONECAPABILITIES']._serialized_end=511
# @@protoc_insertion_point(module_scope)
