# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ServiceDiscoveryResponseMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ServiceDiscoveryResponseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.control import ChannelDescriptorData_pb2 as oaa_dot_control_dot_ChannelDescriptorData__pb2
from oaa.common import DriverPositionEnum_pb2 as oaa_dot_common_dot_DriverPositionEnum__pb2
from oaa.control import HeadUnitInfoData_pb2 as oaa_dot_control_dot_HeadUnitInfoData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1oaa/control/ServiceDiscoveryResponseMessage.proto\x12\x12oaa.proto.messages\x1a\'oaa/control/ChannelDescriptorData.proto\x1a#oaa/common/DriverPositionEnum.proto\x1a\"oaa/control/HeadUnitInfoData.proto\"\x1a\n\x18ServiceDiscoveryFeatureA\"\x1a\n\x18ServiceDiscoveryFeatureB\"\x1a\n\x18ServiceDiscoveryFeatureC\"\x1a\n\x18ServiceDiscoveryFeatureD\"\xea\x03\n\x18ServiceDiscoveryResponse\x12\x33\n\x08\x63hannels\x18\x01 \x03(\x0b\x32!.oaa.proto.data.ChannelDescriptor\x12\x16\n\x0ehead_unit_name\x18\x02 \x01(\t\x12\x11\n\tcar_model\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61r_year\x18\x04 \x01(\t\x12\x12\n\ncar_serial\x18\x05 \x01(\t\x12=\n\x0f\x64river_position\x18\x06 \x01(\x0e\x32$.oaa.proto.enums.DriverPosition.Enum\x12\x1d\n\x15headunit_manufacturer\x18\x07 \x01(\t\x12\x16\n\x0eheadunit_model\x18\x08 \x01(\t\x12\x10\n\x08sw_build\x18\t \x01(\t\x12\x12\n\nsw_version\x18\n \x01(\t\x12\'\n\x1f\x63\x61n_play_native_media_during_vr\x18\x0b \x01(\x08\x12\x1d\n\x15session_configuration\x18\r \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x0e \x01(\t\x12\x19\n\x11probe_for_support\x18\x0f \x01(\x08\x12\x33\n\rheadunit_info\x18\x11 \x01(\x0b\x32\x1c.oaa.proto.data.HeadUnitInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ServiceDiscoveryResponseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEDISCOVERYFEATUREA']._serialized_start=187
  _globals['_SERVICEDISCOVERYFEATUREA']._serialized_end=213
  _globals['_SERVICEDISCOVERYFEATUREB']._serialized_start=215
  _globals['_SERVICEDISCOVERYFEATUREB']._serialized_end=241
  _globals['_SERVICEDISCOVERYFEATUREC']._serialized_start=243
  _globals['_SERVICEDISCOVERYFEATUREC']._serialized_end=269
  _globals['_SERVICEDISCOVERYFEATURED']._serialized_start=271
  _globals['_SERVICEDISCOVERYFEATURED']._serialized_end=297
  _globals['_SERVICEDISCOVERYRESPONSE']._serialized_start=300
  _globals['_SERVICEDISCOVERYRESPONSE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
