# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/control/ShutdownReasonEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/control/ShutdownReasonEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$oaa/control/ShutdownReasonEnum.proto\x12\x0foaa.proto.enums\"\xd0\x01\n\x0eShutdownReason\"\xbd\x01\n\x04\x45num\x12\x12\n\x0eUSER_SELECTION\x10\x01\x12\x11\n\rDEVICE_SWITCH\x10\x02\x12\x11\n\rNOT_SUPPORTED\x10\x03\x12\x1b\n\x17NOT_CURRENTLY_SUPPORTED\x10\x04\x12\x13\n\x0fPROBE_SUPPORTED\x10\x05\x12 \n\x1cWIRELESS_PROJECTION_DISABLED\x10\x06\x12\x0e\n\nPOWER_DOWN\x10\x07\x12\x17\n\x13USER_PROFILE_SWITCH\x10\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.control.ShutdownReasonEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHUTDOWNREASON']._serialized_start=58
  _globals['_SHUTDOWNREASON']._serialized_end=266
  _globals['_SHUTDOWNREASON_ENUM']._serialized_start=77
  _globals['_SHUTDOWNREASON_ENUM']._serialized_end=266
# @@protoc_insertion_point(module_scope)
