# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/phone/PhoneStatusInputMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/phone/PhoneStatusInputMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'oaa/phone/PhoneStatusInputMessage.proto\x12\x12oaa.proto.messages\"F\n\x0ePhoneInputType\x12\x34\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32$.oaa.proto.messages.PhoneInputAction\"s\n\x10PhoneStatusInput\x12\x36\n\ninput_type\x18\x01 \x01(\x0b\x32\".oaa.proto.messages.PhoneInputType\x12\x11\n\tcaller_id\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t*\xc5\x01\n\x10PhoneInputAction\x12\x17\n\x13PHONE_INPUT_UNKNOWN\x10\x00\x12\x12\n\x0ePHONE_INPUT_UP\x10\x01\x12\x14\n\x10PHONE_INPUT_DOWN\x10\x02\x12\x14\n\x10PHONE_INPUT_LEFT\x10\x03\x12\x15\n\x11PHONE_INPUT_RIGHT\x10\x04\x12\x15\n\x11PHONE_INPUT_ENTER\x10\x05\x12\x14\n\x10PHONE_INPUT_BACK\x10\x06\x12\x14\n\x10PHONE_INPUT_CALL\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.phone.PhoneStatusInputMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHONEINPUTACTION']._serialized_start=253
  _globals['_PHONEINPUTACTION']._serialized_end=450
  _globals['_PHONEINPUTTYPE']._serialized_start=63
  _globals['_PHONEINPUTTYPE']._serialized_end=133
  _globals['_PHONESTATUSINPUT']._serialized_start=135
  _globals['_PHONESTATUSINPUT']._serialized_end=250
# @@protoc_insertion_point(module_scope)
