# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelMediaConfigMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelMediaConfigMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.common import PingConfigurationData_pb2 as oaa_dot_common_dot_PingConfigurationData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(oaa/av/AVChannelMediaConfigMessage.proto\x12\x12oaa.proto.messages\x1a&oaa/common/PingConfigurationData.proto\"\xd1\x04\n\x14\x41VChannelMediaConfig\x12\x33\n\x08timing_1\x18\x01 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x16\n\x0e\x66\x65\x61ture_flag_1\x18\x02 \x01(\x08\x12\x33\n\x08timing_2\x18\x03 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x33\n\x08timing_3\x18\x04 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x33\n\x08timing_4\x18\x05 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x33\n\x08timing_5\x18\x06 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x14\n\x0c\x63onfig_value\x18\x07 \x01(\r\x12\x33\n\x08timing_6\x18\x08 \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x16\n\x0e\x66\x65\x61ture_flag_2\x18\t \x01(\x08\x12\x33\n\x08timing_7\x18\n \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x16\n\x0e\x66\x65\x61ture_flag_3\x18\x0b \x01(\x08\x12\x33\n\x08timing_8\x18\x0c \x01(\x0b\x32!.oaa.proto.data.PingConfiguration\x12\x33\n\x08timing_9\x18\r \x01(\x0b\x32!.oaa.proto.data.PingConfiguration')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelMediaConfigMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELMEDIACONFIG']._serialized_start=105
  _globals['_AVCHANNELMEDIACONFIG']._serialized_end=698
# @@protoc_insertion_point(module_scope)
