# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelSetupRequestMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelSetupRequestMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.av import MediaCodecTypeEnum_pb2 as oaa_dot_av_dot_MediaCodecTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)oaa/av/AVChannelSetupRequestMessage.proto\x12\x12oaa.proto.messages\x1a\x1foaa/av/MediaCodecTypeEnum.proto\"W\n\x15\x41VChannelSetupRequest\x12>\n\x10media_codec_type\x18\x01 \x02(\x0e\x32$.oaa.proto.enums.MediaCodecType.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelSetupRequestMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELSETUPREQUEST']._serialized_start=98
  _globals['_AVCHANNELSETUPREQUEST']._serialized_end=185
# @@protoc_insertion_point(module_scope)
