# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVChannelMessageIdsEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVChannelMessageIdsEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$oaa/av/AVChannelMessageIdsEnum.proto\x12\roaa.proto.ids\"\xa2\x05\n\x10\x41VChannelMessage\"\x8d\x05\n\x04\x45num\x12&\n\"AV_MEDIA_WITH_TIMESTAMP_INDICATION\x10\x00\x12\x17\n\x13\x41V_MEDIA_INDICATION\x10\x01\x12\x13\n\rSETUP_REQUEST\x10\x80\x80\x02\x12\x16\n\x10START_INDICATION\x10\x81\x80\x02\x12\x15\n\x0fSTOP_INDICATION\x10\x82\x80\x02\x12\x14\n\x0eSETUP_RESPONSE\x10\x83\x80\x02\x12\x1d\n\x17\x41V_MEDIA_ACK_INDICATION\x10\x84\x80\x02\x12\x1b\n\x15\x41V_INPUT_OPEN_REQUEST\x10\x85\x80\x02\x12\x1c\n\x16\x41V_INPUT_OPEN_RESPONSE\x10\x86\x80\x02\x12\x19\n\x13VIDEO_FOCUS_REQUEST\x10\x87\x80\x02\x12\x1c\n\x16VIDEO_FOCUS_INDICATION\x10\x88\x80\x02\x12\x1e\n\x18VIDEO_FOCUS_NOTIFICATION\x10\x89\x80\x02\x12\x1e\n\x18UPDATE_UI_CONFIG_REQUEST\x10\x8a\x80\x02\x12\x1c\n\x16UPDATE_UI_CONFIG_REPLY\x10\x8b\x80\x02\x12\x15\n\x0f\x41UDIO_UNDERFLOW\x10\x8c\x80\x02\x12\x12\n\x0c\x41\x43TION_TAKEN\x10\x8d\x80\x02\x12\x18\n\x12OVERLAY_PARAMETERS\x10\x8e\x80\x02\x12\x13\n\rOVERLAY_START\x10\x8f\x80\x02\x12\x12\n\x0cOVERLAY_STOP\x10\x90\x80\x02\x12\x1c\n\x16OVERLAY_SESSION_UPDATE\x10\x91\x80\x02\x12!\n\x1bUPDATE_HU_UI_CONFIG_REQUEST\x10\x92\x80\x02\x12\"\n\x1cUPDATE_HU_UI_CONFIG_RESPONSE\x10\x93\x80\x02\x12\x11\n\x0bMEDIA_STATS\x10\x94\x80\x02\x12\x13\n\rMEDIA_OPTIONS\x10\x95\x80\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVChannelMessageIdsEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVCHANNELMESSAGE']._serialized_start=56
  _globals['_AVCHANNELMESSAGE']._serialized_end=730
  _globals['_AVCHANNELMESSAGE_ENUM']._serialized_start=77
  _globals['_AVCHANNELMESSAGE_ENUM']._serialized_end=730
# @@protoc_insertion_point(module_scope)
