# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/av/AVInputChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/av/AVInputChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.av import AVStreamTypeEnum_pb2 as oaa_dot_av_dot_AVStreamTypeEnum__pb2
from oaa.audio import AudioConfigData_pb2 as oaa_dot_audio_dot_AudioConfigData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1foaa/av/AVInputChannelData.proto\x12\x0eoaa.proto.data\x1a\x1doaa/av/AVStreamTypeEnum.proto\x1a\x1foaa/audio/AudioConfigData.proto\"|\n\x0e\x41VInputChannel\x12\x37\n\x0bstream_type\x18\x01 \x01(\x0e\x32\".oaa.proto.enums.AVStreamType.Enum\x12\x31\n\x0c\x61udio_config\x18\x02 \x01(\x0b\x32\x1b.oaa.proto.data.AudioConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.av.AVInputChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVINPUTCHANNEL']._serialized_start=115
  _globals['_AVINPUTCHANNEL']._serialized_end=239
# @@protoc_insertion_point(module_scope)
