wireplumber.profiles = {
  main = {
    monitor.bluez.seat-monitoring = disabled
  }
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source hfp_hf hfp_ag hsp_hs hsp_ag ]
  bluez5.hfphsp-backend = "native"
  bluez5.enable-sbc-xq = true
  bluez5.enable-msbc = true
  bluez5.enable-sbc = true
  bluez5.enable-hw-volume = true
  bluez5.hfp-hf.disable-nrec = false
}
