# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/GearEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/GearEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19oaa/sensor/GearEnum.proto\x12\x0foaa.proto.enums\"\xb1\x01\n\x04Gear\"\xa8\x01\n\x04\x45num\x12\x0b\n\x07NEUTRAL\x10\x00\x12\t\n\x05\x46IRST\x10\x01\x12\n\n\x06SECOND\x10\x02\x12\t\n\x05THIRD\x10\x03\x12\n\n\x06\x46OURTH\x10\x04\x12\t\n\x05\x46IFTH\x10\x05\x12\t\n\x05SIXTH\x10\x06\x12\x0b\n\x07SEVENTH\x10\x07\x12\n\n\x06\x45IGHTH\x10\x08\x12\t\n\x05NINTH\x10\t\x12\t\n\x05TENTH\x10\n\x12\t\n\x05\x44RIVE\x10\x64\x12\x08\n\x04PARK\x10\x65\x12\x0b\n\x07REVERSE\x10\x66')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.GearEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEAR']._serialized_start=47
  _globals['_GEAR']._serialized_end=224
  _globals['_GEAR_ENUM']._serialized_start=56
  _globals['_GEAR_ENUM']._serialized_end=224
# @@protoc_insertion_point(module_scope)
