# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/SensorChannelData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/SensorChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oaa.sensor import SensorData_pb2 as oaa_dot_sensor_dot_SensorData__pb2
from oaa.sensor import FuelTypeEnum_pb2 as oaa_dot_sensor_dot_FuelTypeEnum__pb2
from oaa.sensor import EVConnectorTypeEnum_pb2 as oaa_dot_sensor_dot_EVConnectorTypeEnum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"oaa/sensor/SensorChannelData.proto\x12\x0eoaa.proto.data\x1a\x1boaa/sensor/SensorData.proto\x1a\x1doaa/sensor/FuelTypeEnum.proto\x1a$oaa/sensor/EVConnectorTypeEnum.proto\"\xcd\x01\n\rSensorChannel\x12\'\n\x07sensors\x18\x01 \x03(\x0b\x32\x16.oaa.proto.data.Sensor\x12!\n\x19location_characterization\x18\x02 \x01(\r\x12\x32\n\nfuel_types\x18\x03 \x03(\x0e\x32\x1e.oaa.proto.enums.FuelType.Enum\x12<\n\rev_connectors\x18\x04 \x03(\x0e\x32%.oaa.proto.enums.EVConnectorType.Enum')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.SensorChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORCHANNEL']._serialized_start=153
  _globals['_SENSORCHANNEL']._serialized_end=358
# @@protoc_insertion_point(module_scope)
