# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/sensor/SensorTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/sensor/SensorTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1foaa/sensor/SensorTypeEnum.proto\x12\x0foaa.proto.enums\"\xaa\x03\n\nSensorType\"\x9b\x03\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08LOCATION\x10\x01\x12\x0b\n\x07\x43OMPASS\x10\x02\x12\r\n\tCAR_SPEED\x10\x03\x12\x07\n\x03RPM\x10\x04\x12\x0c\n\x08ODOMETER\x10\x05\x12\x0e\n\nFUEL_LEVEL\x10\x06\x12\x11\n\rPARKING_BRAKE\x10\x07\x12\x08\n\x04GEAR\x10\x08\x12\x0f\n\x0b\x44IAGNOSTICS\x10\t\x12\x0e\n\nNIGHT_DATA\x10\n\x12\x0f\n\x0b\x45NVIRONMENT\x10\x0b\x12\x08\n\x04HVAC\x10\x0c\x12\x12\n\x0e\x44RIVING_STATUS\x10\r\x12\x11\n\rDEAD_RECONING\x10\x0e\x12\r\n\tPASSENGER\x10\x0f\x12\x08\n\x04\x44OOR\x10\x10\x12\t\n\x05LIGHT\x10\x11\x12\x08\n\x04TIRE\x10\x12\x12\t\n\x05\x41\x43\x43\x45L\x10\x13\x12\x08\n\x04GYRO\x10\x14\x12\x07\n\x03GPS\x10\x15\x12\r\n\tTOLL_CARD\x10\x16\x12\x18\n\x14VEHICLE_ENERGY_MODEL\x10\x17\x12\x0b\n\x07TRAILER\x10\x18\x12\x1c\n\x18RAW_VEHICLE_ENERGY_MODEL\x10\x19\x12\x18\n\x14RAW_EV_TRIP_SETTINGS\x10\x1a\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.sensor.SensorTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORTYPE']._serialized_start=53
  _globals['_SENSORTYPE']._serialized_end=479
  _globals['_SENSORTYPE_ENUM']._serialized_start=68
  _globals['_SENSORTYPE_ENUM']._serialized_end=479
# @@protoc_insertion_point(module_scope)
