# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oaa/notification/NotificationTypeEnum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oaa/notification/NotificationTypeEnum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+oaa/notification/NotificationTypeEnum.proto\x12\x0foaa.proto.enums\"\x86\x05\n\x10NotificationType\"\xf1\x04\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TOAST\x10\x01\x12\t\n\x05MEDIA\x10\x02\x12\x06\n\x02IM\x10\x03\x12\x0c\n\x08NAV_HERO\x10\x04\x12\x07\n\x03SMS\x10\x05\x12\x08\n\x04\x43\x41LL\x10\x06\x12\x0f\n\x0bRECENT_CALL\x10\x07\x12\x12\n\x0eGMM_SUGGESTION\x10\x08\x12\x17\n\x13NOW_PLAYING_CHANGED\x10\t\x12\x0f\n\x0bNOW_WEATHER\x10\n\x12\x0f\n\x0bNOW_TRAFFIC\x10\x0b\x12\x0e\n\nNOW_SPORTS\x10\x0c\x12\x0e\n\nNOW_STOCKS\x10\r\x12\x0f\n\x0bNOW_TRANSIT\x10\x0e\x12\x0f\n\x0bNOW_FLIGHTS\x10\x0f\x12\x0e\n\nNOW_PLACES\x10\x10\x12\x0e\n\nNOW_EVENTS\x10\x11\x12\x10\n\x0cNOW_PACKAGES\x10\x12\x12\x15\n\x11NOW_PUBLIC_ALERTS\x10\x13\x12\x11\n\rNOW_REMINDERS\x10\x14\x12\x17\n\x13NOW_RESEARCH_TOPICS\x10\x15\x12\x11\n\rNOW_BIRTHDAYS\x10\x16\x12\x0e\n\nNAV_NORMAL\x10\x17\x12\x07\n\x03SDK\x10\x18\x12\x12\n\x0eNAV_SUGGESTION\x10\x19\x12\x0f\n\x0b\x42\x41TTERY_LOW\x10\x1a\x12\x0f\n\x0bNOW_ROUTINE\x10\x1b\x12\x1c\n\x18VISUAL_PREVIEW_DISCOVERY\x10\x1c\x12\r\n\tDEVELOPER\x10\x1d\x12\x18\n\x14OPT_IN_ABOVE_ONGOING\x10\x1e\x12\x18\n\x14OPT_IN_BELOW_ONGOING\x10\x1f\x12\x17\n\x13VANAGON_DEPRECATION\x10 \x12\x19\n\x15VANAGON_DEPRECATION_2\x10!\x12\x12\n\x0eOS_DEPRECATION\x10\"b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oaa.notification.NotificationTypeEnum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONTYPE']._serialized_start=65
  _globals['_NOTIFICATIONTYPE']._serialized_end=711
  _globals['_NOTIFICATIONTYPE_ENUM']._serialized_start=86
  _globals['_NOTIFICATIONTYPE_ENUM']._serialized_end=711
# @@protoc_insertion_point(module_scope)
